# Generated by Django 6.0.3 on 2026-04-09 16:39

import django.core.validators
import django.db.models.deletion
from commons.shared.storage_utils import caminho_documento
import fluxo.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credores", "0001_initial"),
        ("fluxo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusChoicesSuprimentoDeFundos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSuprimentoDeFundos",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor do Numerário Liberado (R$)",
                    ),
                ),
                (
                    "taxa_saque",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor da Taxa de Saque (R$)",
                    ),
                ),
                (
                    "lotacao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Lotação"
                    ),
                ),
                ("inicio_periodo", models.DateField(verbose_name="Período Inicial (De)")),
                ("fim_periodo", models.DateField(verbose_name="Período Final (Até)")),
                (
                    "data_recibo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Carga na Conta"
                    ),
                ),
                (
                    "data_devolucao_saldo",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Devolução de Saldo Remanescente",
                    ),
                ),
                (
                    "valor_devolvido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Devolvido (R$)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "suprido",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo": "PF"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.credor",
                        verbose_name="Suprido",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="suprimentos.statuschoicessuprimentodefundos",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical suprimento de fundos",
                "verbose_name_plural": "historical suprimento de fundoss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SuprimentoDeFundos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor do Numerário Liberado (R$)",
                    ),
                ),
                (
                    "taxa_saque",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor da Taxa de Saque (R$)",
                    ),
                ),
                (
                    "lotacao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Lotação"
                    ),
                ),
                ("inicio_periodo", models.DateField(verbose_name="Período Inicial (De)")),
                ("fim_periodo", models.DateField(verbose_name="Período Final (Até)")),
                (
                    "data_recibo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Carga na Conta"
                    ),
                ),
                (
                    "data_devolucao_saldo",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Devolução de Saldo Remanescente",
                    ),
                ),
                (
                    "valor_devolvido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Devolvido (R$)",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suprimentos",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suprimentos.statuschoicessuprimentodefundos",
                    ),
                ),
                (
                    "suprido",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "PF"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.credor",
                        verbose_name="Suprido",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("acesso_backoffice", "Acesso ao backoffice de suprimentos"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(fim_periodo__gte=models.F("inicio_periodo")),
                        name="suprimento_periodo_valido_chk",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(data_devolucao_saldo__isnull=True)
                            | models.Q(data_recibo__isnull=True)
                            | models.Q(data_devolucao_saldo__gte=models.F("data_recibo"))
                        ),
                        name="suprimento_devolucao_gte_recibo_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(valor_liquido__gte=0),
                        name="suprimento_valor_liquido_nao_negativo_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(taxa_saque__gte=0),
                        name="suprimento_taxa_saque_nao_negativa_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(valor_devolvido__isnull=True)
                        | models.Q(valor_devolvido__gte=0),
                        name="suprimento_valor_devolvido_nao_negativo_chk",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoSuprimentoDeFundos",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.tiposdedocumento",
                    ),
                ),
                (
                    "suprimento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="suprimentos.suprimentodefundos",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento suprimento de fundos",
                "verbose_name_plural": "historical documento suprimento de fundoss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDespesaSuprimento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Compra")),
                (
                    "estabelecimento",
                    models.CharField(
                        max_length=150, verbose_name="Estabelecimento (Credor)"
                    ),
                ),
                (
                    "cnpj_cpf",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CNPJ/CPF"
                    ),
                ),
                (
                    "detalhamento",
                    models.CharField(
                        max_length=255, verbose_name="Material/Serviço Adquirido"
                    ),
                ),
                (
                    "nota_fiscal",
                    models.CharField(
                        max_length=50, verbose_name="Nº Nota Fiscal/Cupom"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Pago (R$)",
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                        verbose_name="Arquivo Único (Solicitação + NF)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suprimento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="suprimentos.suprimentodefundos",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical despesa suprimento",
                "verbose_name_plural": "historical despesa suprimentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentoSuprimentoDeFundos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=caminho_documento,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fluxo.tiposdedocumento",
                    ),
                ),
                (
                    "suprimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="suprimentos.suprimentodefundos",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DespesaSuprimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Compra")),
                (
                    "estabelecimento",
                    models.CharField(
                        max_length=150, verbose_name="Estabelecimento (Credor)"
                    ),
                ),
                (
                    "cnpj_cpf",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CNPJ/CPF"
                    ),
                ),
                (
                    "detalhamento",
                    models.CharField(
                        max_length=255, verbose_name="Material/Serviço Adquirido"
                    ),
                ),
                (
                    "nota_fiscal",
                    models.CharField(
                        max_length=50, verbose_name="Nº Nota Fiscal/Cupom"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Pago (R$)",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=caminho_documento,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                        verbose_name="Arquivo Único (Solicitação + NF)",
                    ),
                ),
                (
                    "suprimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="suprimentos.suprimentodefundos",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(valor__gte=0),
                        name="despesa_valor_nao_negativo_chk",
                    ),
                ],
            },
        ),
    ]
