# Generated by Django 6.0.3 on 2026-04-09 16:39

import django.core.validators
import django.db.models.deletion
import commons.shared.file_validators
from commons.shared.storage_utils import caminho_documento
import pagamentos.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("credores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormasDePagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forma_de_pagamento", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReuniaoConselho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        help_text="Ex: 16 para a 16ª Reunião",
                        verbose_name="Número da Reunião",
                    ),
                ),
                (
                    "data_reuniao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Reunião"
                    ),
                ),
                (
                    "trimestre_referencia",
                    models.CharField(
                        help_text="Ex: 1º Trimestre / 2026",
                        max_length=50,
                        verbose_name="Trimestre/Ano de Referência",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada/Em Montagem"),
                            ("EM_ANALISE", "Em Análise pelo Conselho"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="AGENDADA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reunião do Conselho",
                "verbose_name_plural": "Reuniões do Conselho",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="StatusChoicesPendencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusChoicesProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiposDeDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_documento", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiposDePagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_pagamento", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiposDePendencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_pendencia", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssinaturaAutentique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "tipo_documento",
                    models.CharField(
                        help_text="Ex: SCD, PCD, AUTORIZACAO",
                        max_length=50,
                        verbose_name="Tipo do Documento",
                    ),
                ),
                (
                    "autentique_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="ID Autentique",
                    ),
                ),
                (
                    "autentique_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="URL para Assinatura",
                    ),
                ),
                (
                    "dados_signatarios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Dados dos Signatários",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PENDENTE", "Pendente"),
                            ("ASSINADO", "Assinado"),
                            ("REJEITADO", "Rejeitado"),
                            ("ERRO", "Erro"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assinaturas_rascunho/",
                        verbose_name="Arquivo (Rascunho)",
                    ),
                ),
                (
                    "arquivo_assinado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_assinados/",
                        verbose_name="Arquivo Assinado",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assinaturas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAssinaturaAutentique",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "tipo_documento",
                    models.CharField(
                        help_text="Ex: SCD, PCD, AUTORIZACAO",
                        max_length=50,
                        verbose_name="Tipo do Documento",
                    ),
                ),
                (
                    "autentique_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID Autentique",
                    ),
                ),
                (
                    "autentique_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="URL para Assinatura",
                    ),
                ),
                (
                    "dados_signatarios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Dados dos Signatários",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PENDENTE", "Pendente"),
                            ("ASSINADO", "Assinado"),
                            ("REJEITADO", "Rejeitado"),
                            ("ERRO", "Erro"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Arquivo (Rascunho)",
                    ),
                ),
                (
                    "arquivo_assinado",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Arquivo Assinado",
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "criador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical assinatura autentique",
                "verbose_name_plural": "historical assinatura autentiques",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRegistroAcessoArquivo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome_arquivo", models.CharField(max_length=500)),
                ("data_acesso", models.DateTimeField(blank=True, editable=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Registro de Acesso a Arquivo",
                "verbose_name_plural": "historical Registros de Acesso a Arquivos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extraorcamentario",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se este processo não utiliza dotação orçamentária (ex: cauções).",
                        verbose_name="Extraorçamentário",
                    ),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "n_pagamento_siscac",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("observacao", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "detalhamento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "arquivo_final",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="processos_arquivados/",
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                        verbose_name="Processo Consolidado",
                    ),
                ),
                (
                    "em_contingencia",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que existe uma Contingência ativa para este processo. Nenhuma operação financeira pode ser realizada enquanto este flag estiver ativo.",
                        verbose_name="Em Contingência",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processos_sacados",
                        to="credores.contasbancarias",
                        verbose_name="Conta Sacada",
                    ),
                ),
                (
                    "credor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.credor",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.formasdepagamento",
                    ),
                ),
                (
                    "reuniao_conselho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processos_em_pauta",
                        to="pagamentos.reuniaoconselho",
                        verbose_name="Reunião do Conselho",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.statuschoicesprocesso",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tagchoices",
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tiposdepagamento",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "operador_contas_a_pagar",
                        "Pode acessar as telas gerais do sistema financeiro",
                    ),
                    (
                        "pode_visualizar_processos_pagamento",
                        "Pode visualizar processos de pagamento",
                    ),
                    (
                        "pode_editar_processos_pagamento",
                        "Pode editar processos de pagamento",
                    ),
                    (
                        "pode_operar_contas_pagar",
                        "Pode empenhar, triar notas e fazer conferência",
                    ),
                    (
                        "pode_aprovar_contingencia_supervisor",
                        "Pode aprovar contingências na etapa de supervisão/gerência",
                    ),
                    (
                        "pode_atestar_liquidacao",
                        "Pode atestar notas fiscais (Fiscal do Contrato)",
                    ),
                    (
                        "pode_autorizar_pagamento",
                        "Pode autorizar pagamentos (Ordenador)",
                    ),
                    ("pode_contabilizar", "Pode registrar a contabilização (Contador)"),
                    ("pode_auditar_conselho", "Pode aprovar no Conselho Fiscal"),
                    (
                        "pode_arquivar",
                        "Pode realizar o arquivamento definitivo de processos",
                    ),
                    (
                        "pode_visualizar_verbas",
                        "Pode visualizar painéis e listas de verbas indenizatórias",
                    ),
                    ("pode_criar_diarias", "Pode cadastrar solicitações de diárias"),
                    ("pode_importar_diarias", "Pode importar diárias em lote"),
                    ("pode_gerenciar_diarias", "Pode editar diárias e seus documentos"),
                    ("pode_autorizar_diarias", "Pode autorizar e aprovar diárias"),
                    (
                        "pode_gerenciar_reembolsos",
                        "Pode cadastrar e editar reembolsos de combustível",
                    ),
                    ("pode_gerenciar_jetons", "Pode cadastrar e editar jetons"),
                    (
                        "pode_gerenciar_auxilios",
                        "Pode cadastrar e editar auxílios representação",
                    ),
                    (
                        "pode_agrupar_verbas",
                        "Pode agrupar verbas em processos de pagamento",
                    ),
                    (
                        "pode_gerenciar_processos_verbas",
                        "Pode editar processos originados de verbas indenizatórias",
                    ),
                    (
                        "pode_sincronizar_diarias_siscac",
                        "Pode sincronizar/importar diárias via SISCAC",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDevolucao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "valor_devolvido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("data_devolucao", models.DateField()),
                ("motivo", models.TextField()),
                (
                    "comprovante",
                    models.TextField(
                        help_text="Comprovante de depósito/GRU",
                        max_length=100,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Devolução",
                "verbose_name_plural": "historical Devoluções",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContingencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(blank=True, editable=False)),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Motivo detalhado para a quebra de fluxo/retificação."
                    ),
                ),
                (
                    "dados_propostos",
                    models.JSONField(
                        default=dict,
                        help_text="Dicionário JSON contendo o estado exato dos campos que serão alterados no Processo (ex: {'credor_id': 5}).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE_SUPERVISOR", "Pendente Supervisor"),
                            ("PENDENTE_ORDENADOR", "Pendente Ordenador de Despesa"),
                            ("PENDENTE_CONSELHO", "Pendente Conselho Fiscal"),
                            ("PENDENTE_CONTADOR", "Pendente Revisão da Contadora"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                        ],
                        default="PENDENTE_SUPERVISOR",
                        max_length=30,
                    ),
                ),
                ("exige_aprovacao_ordenador", models.BooleanField(default=False)),
                ("exige_aprovacao_conselho", models.BooleanField(default=False)),
                ("exige_revisao_contadora", models.BooleanField(default=True)),
                ("parecer_supervisor", models.TextField(blank=True, null=True)),
                (
                    "data_aprovacao_supervisor",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parecer_ordenador", models.TextField(blank=True, null=True)),
                (
                    "data_aprovacao_ordenador",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parecer_conselho", models.TextField(blank=True, null=True)),
                (
                    "data_aprovacao_conselho",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parecer_contadora", models.TextField(blank=True, null=True)),
                ("data_revisao_contadora", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "aprovado_por_conselho",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprovado_por_ordenador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprovado_por_supervisor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisado_por_contadora",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contingência",
                "verbose_name_plural": "historical Contingências",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Devolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_devolvido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("data_devolucao", models.DateField()),
                ("motivo", models.TextField()),
                (
                    "comprovante",
                    models.FileField(
                        help_text="Comprovante de depósito/GRU",
                        upload_to="devolucoes/",
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devolucoes",
                        to="pagamentos.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolução",
                "verbose_name_plural": "Devoluções",
                "ordering": ["-data_devolucao"],
            },
        ),
        migrations.CreateModel(
            name="Contingencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Motivo detalhado para a quebra de fluxo/retificação."
                    ),
                ),
                (
                    "dados_propostos",
                    models.JSONField(
                        default=dict,
                        help_text="Dicionário JSON contendo o estado exato dos campos que serão alterados no Processo (ex: {'credor_id': 5}).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE_SUPERVISOR", "Pendente Supervisor"),
                            ("PENDENTE_ORDENADOR", "Pendente Ordenador de Despesa"),
                            ("PENDENTE_CONSELHO", "Pendente Conselho Fiscal"),
                            ("PENDENTE_CONTADOR", "Pendente Revisão da Contadora"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                        ],
                        default="PENDENTE_SUPERVISOR",
                        max_length=30,
                    ),
                ),
                ("exige_aprovacao_ordenador", models.BooleanField(default=False)),
                ("exige_aprovacao_conselho", models.BooleanField(default=False)),
                ("exige_revisao_contadora", models.BooleanField(default=True)),
                ("parecer_supervisor", models.TextField(blank=True, null=True)),
                (
                    "data_aprovacao_supervisor",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parecer_ordenador", models.TextField(blank=True, null=True)),
                (
                    "data_aprovacao_ordenador",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parecer_conselho", models.TextField(blank=True, null=True)),
                (
                    "data_aprovacao_conselho",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parecer_contadora", models.TextField(blank=True, null=True)),
                ("data_revisao_contadora", models.DateTimeField(blank=True, null=True)),
                (
                    "aprovado_por_conselho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cont_conselho",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprovado_por_ordenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cont_ordenadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprovado_por_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cont_supervisionadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisado_por_contadora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cont_revisadas_contadora",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contingencias_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contingencias",
                        to="pagamentos.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contingência",
                "verbose_name_plural": "Contingências",
                "ordering": ["-data_solicitacao"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAcessoArquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_arquivo", models.CharField(max_length=500)),
                ("data_acesso", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Acesso a Arquivo",
                "verbose_name_plural": "Registros de Acesso a Arquivos",
                "ordering": ["-data_acesso"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoOrcamentario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "numero_nota_empenho",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_empenho", models.DateField(blank=True, null=True)),
                (
                    "ano_exercicio",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                            (2026, 2026),
                            (2027, 2027),
                            (2028, 2028),
                            (2029, 2029),
                            (2030, 2030),
                            (2031, 2031),
                            (2032, 2032),
                            (2033, 2033),
                            (2034, 2034),
                        ],
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento orcamentario",
                "verbose_name_plural": "historical documento orcamentarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoProcesso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "imutavel",
                    models.BooleanField(
                        default=False,
                        help_text="Documento bloqueado para exclusão. Definido automaticamente durante a etapa de Conferência.",
                        verbose_name="Imutável",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Documento do Processo",
                "verbose_name_plural": "historical Documentos do Processo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalComprovanteDePagamento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "numero_comprovante",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número do Comprovante",
                    ),
                ),
                (
                    "credor_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Credor (Texto)",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.processo",
                        verbose_name="Processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Comprovante de Pagamento",
                "verbose_name_plural": "historical Comprovantes de Pagamento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentoOrcamentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=caminho_documento,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "numero_nota_empenho",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_empenho", models.DateField(blank=True, null=True)),
                (
                    "ano_exercicio",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                            (2026, 2026),
                            (2027, 2027),
                            (2028, 2028),
                            (2029, 2029),
                            (2030, 2030),
                            (2031, 2031),
                            (2032, 2032),
                            (2033, 2033),
                            (2034, 2034),
                        ],
                        null=True,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_orcamentarios",
                        to="pagamentos.processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_empenho", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ComprovanteDePagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=caminho_documento,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
                (
                    "numero_comprovante",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número do Comprovante",
                    ),
                ),
                (
                    "credor_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Credor (Texto)",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprovantes_pagamento",
                        to="pagamentos.processo",
                        verbose_name="Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante de Pagamento",
                "verbose_name_plural": "Comprovantes de Pagamento",
            },
        ),
        migrations.CreateModel(
            name="DocumentoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=caminho_documento,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "imutavel",
                    models.BooleanField(
                        default=False,
                        help_text="Documento bloqueado para exclusão. Definido automaticamente durante a etapa de Conferência.",
                        verbose_name="Imutável",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="pagamentos.processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Processo",
                "verbose_name_plural": "Documentos do Processo",
            },
        ),
        migrations.CreateModel(
            name="Boleto_Bancario",
            fields=[
                (
                    "documentoprocesso_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pagamentos.documentoprocesso",
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Código de Barras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto_Bancario",
                "verbose_name_plural": "Boleto_Bancario",
            },
            bases=("pagamentos.documentoprocesso",),
        ),
        migrations.AddField(
            model_name="tiposdedocumento",
            name="tipo_de_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdepagamento",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalProcesso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "extraorcamentario",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se este processo não utiliza dotação orçamentária (ex: cauções).",
                        verbose_name="Extraorçamentário",
                    ),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "n_pagamento_siscac",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("observacao", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "detalhamento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "arquivo_final",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[pagamentos.validators.validar_arquivo_seguro],
                        verbose_name="Processo Consolidado",
                    ),
                ),
                (
                    "em_contingencia",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que existe uma Contingência ativa para este processo. Nenhuma operação financeira pode ser realizada enquanto este flag estiver ativo.",
                        verbose_name="Em Contingência",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.contasbancarias",
                        verbose_name="Conta Sacada",
                    ),
                ),
                (
                    "credor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.credor",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.formasdepagamento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reuniao_conselho",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.reuniaoconselho",
                        verbose_name="Reunião do Conselho",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.statuschoicesprocesso",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tagchoices",
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tiposdepagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical processo",
                "verbose_name_plural": "historical processos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pendencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendencias",
                        to="pagamentos.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.statuschoicespendencias",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tiposdependencias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPendencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.statuschoicespendencias",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tiposdependencias",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pendencia",
                "verbose_name_plural": "historical pendencias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="tiposdedocumento",
            constraint=models.UniqueConstraint(
                fields=("tipo_de_documento", "tipo_de_pagamento"),
                name="unique_documento_por_pagamento",
            ),
        ),
    ]
