# Generated by Django 6.0.3 on 2026-04-23 01:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_delete_tiposdedocumento_delete_tiposdepagamento'),
        ('suprimentos', '0003_prestacaocontassuprimento'),
        ('verbas_indenizatorias', '0003_remove_apostila_add_contingencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelamentoProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCESSO', 'Processo'), ('DIARIA', 'Diária'), ('REEMBOLSO', 'Reembolso'), ('JETON', 'Jeton'), ('AUXILIO', 'Auxílio'), ('SUPRIMENTO', 'Suprimento de Fundos')], max_length=20)),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('auxilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='verbas_indenizatorias.auxiliorepresentacao')),
                ('diaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='verbas_indenizatorias.diaria')),
                ('jeton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='verbas_indenizatorias.jeton')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='pagamentos.processo')),
                ('reembolso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='verbas_indenizatorias.reembolsocombustivel')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('suprimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='suprimentos.suprimentodefundos')),
            ],
            options={
                'verbose_name': 'Cancelamento',
                'verbose_name_plural': 'Cancelamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCancelamentoProcessual',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCESSO', 'Processo'), ('DIARIA', 'Diária'), ('REEMBOLSO', 'Reembolso'), ('JETON', 'Jeton'), ('AUXILIO', 'Auxílio'), ('SUPRIMENTO', 'Suprimento de Fundos')], max_length=20)),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auxilio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verbas_indenizatorias.auxiliorepresentacao')),
                ('diaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verbas_indenizatorias.diaria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jeton', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verbas_indenizatorias.jeton')),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pagamentos.processo')),
                ('reembolso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verbas_indenizatorias.reembolsocombustivel')),
                ('registrado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suprimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suprimentos.suprimentodefundos')),
            ],
            options={
                'verbose_name': 'historical Cancelamento',
                'verbose_name_plural': 'historical Cancelamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
