# Generated by Django 6.0.3 on 2026-04-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagamentos",
            "0002_formaspagamento_opcoesetiqueta_statusopcoespendencia_and_more",
        ),
        ("suprimentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentosuprimentodefundos",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentosuprimentodefundos",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.tiposdocumento",
            ),
        ),
    ]
