# Generated by Django 6.0.3 on 2026-04-21 21:49

import commons.shared.file_validators
import commons.shared.storage_utils
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_alter_documentosuprimentodefundos_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrestacaoContasSuprimento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENVIADA', 'Aguardando Revisão'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=10)),
                ('comprovante_devolucao', models.TextField(blank=True, help_text='Comprovante de depósito/GRU do saldo remanescente devolvido.', max_length=100, null=True, validators=[commons.shared.file_validators.validar_arquivo_seguro], verbose_name='Comprovante de Devolução de Saldo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução do Saldo')),
                ('termo_fidedignidade_assinado', models.BooleanField(default=False, verbose_name='Termo de fidedignidade assinado')),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('encerrado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submetido_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suprimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suprimentos.suprimentodefundos')),
            ],
            options={
                'verbose_name': 'historical prestacao contas suprimento',
                'verbose_name_plural': 'historical prestacao contas suprimentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PrestacaoContasSuprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENVIADA', 'Aguardando Revisão'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=10)),
                ('comprovante_devolucao', models.FileField(blank=True, help_text='Comprovante de depósito/GRU do saldo remanescente devolvido.', null=True, upload_to=commons.shared.storage_utils.caminho_documento, validators=[commons.shared.file_validators.validar_arquivo_seguro], verbose_name='Comprovante de Devolução de Saldo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução do Saldo')),
                ('termo_fidedignidade_assinado', models.BooleanField(default=False, verbose_name='Termo de fidedignidade assinado')),
                ('submetido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_suprimento_encerradas', to=settings.AUTH_USER_MODEL)),
                ('submetido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_suprimento_submetidas', to=settings.AUTH_USER_MODEL)),
                ('suprimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestacao_contas', to='suprimentos.suprimentodefundos')),
            ],
        ),
    ]
