# Generated by Django 6.0.2 on 2026-02-07 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=50, verbose_name='CPF/CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitente', models.CharField(max_length=50, verbose_name='Emitente')),
                ('numero_nota_fiscal', models.CharField(max_length=50, verbose_name='Número da Nota Fiscal')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Bruto')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Liquido')),
                ('impostos', models.CharField(max_length=50, verbose_name='Nota de Empenho')),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='processos_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraorcamentario', models.BooleanField(default=False)),
                ('empenhado', models.BooleanField(default=True)),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('routine', 'Routine Payments'), ('verbas', 'Verbas Indenizatórias'), ('eventuais', 'Pagamentos Eventuais'), ('remuneracao', 'Remuneração'), ('repasses', 'Repasses')], max_length=50, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('gerenciador', 'Gerenciador/Boleto'), ('transferencia', 'Transferência'), ('pix', 'PIX'), ('debito', 'Débito Automático'), ('pre_pago', 'Cartão Pré-pago')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pendencias', 'Tem pendências'), ('conferencia', 'Para conferência'), ('concluido', 'Concluído')], default='conferencia', max_length=50)),
                ('n_nota_empenho', models.CharField(blank=True, max_length=50, null=True)),
                ('credor', models.CharField(blank=True, max_length=200, null=True)),
                ('data_empenho', models.DateField(default=django.utils.timezone.now)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ano_exercicio', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2026)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verba_Indenizatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('numero_sequencial', models.CharField(max_length=50, verbose_name='Número Sequencial')),
                ('beneficiario', models.CharField(blank=True, null=True, verbose_name='Beneficiário(a)')),
                ('data_saida', models.DateField(verbose_name='Data de Saída')),
                ('data_retorno', models.DateField(verbose_name='Data de Retorno')),
                ('cidade_origem', models.CharField(max_length=50, verbose_name='Cidade de Origem')),
                ('cidade_destino', models.CharField(max_length=50, verbose_name='Cidade(s) de Destino')),
                ('objetivo', models.CharField(max_length=50, verbose_name='Objetivo')),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='processos_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('siscac', 'Docs. SISCAC'), ('oc', 'Ordem de Compra (OC)'), ('nf', 'Nota Fiscal (NF)'), ('boleto', 'Boleto'), ('comprovante', 'Comprovante'), ('outros', 'Outros')], max_length=20)),
                ('arquivo', models.FileField(upload_to='processos_docs/')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo no processo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.processo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
