# Generated by Django 6.0.2 on 2026-02-09 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: IRRF, ISS, 1708', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emitente', models.CharField(max_length=255)),
                ('cnpj_emitente', models.CharField(max_length=20)),
                ('numero_nota', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sem_retencao', models.BooleanField(default=False, verbose_name='Sem Retenção de Impostos')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='processos.processo')),
            ],
        ),
        migrations.DeleteModel(
            name='Nota_Fiscal',
        ),
        migrations.AddField(
            model_name='imposto',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impostos', to='processos.notafiscal'),
        ),
    ]
