# Generated by Django 6.0.2 on 2026-02-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_imposto_notafiscal_delete_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notafiscal',
            old_name='numero_nota',
            new_name='numero_nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='sem_retencao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='empenhado',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='entidade_imune_isenta',
            field=models.BooleanField(default=False, verbose_name='Entidade Imune ou Isenta'),
        ),
        migrations.AddField(
            model_name='processo',
            name='detalhamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='id_unico_interno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='n_pagamento_siscac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='path_process_folder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='verba_indenizatoria',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='verbas_indenizatorias/'),
        ),
        migrations.DeleteModel(
            name='Imposto',
        ),
    ]
