# Generated by Django 6.0.2 on 2026-02-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_rename_numero_nota_notafiscal_numero_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='entidade_imune_isenta',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='id_unico_interno',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='dados_retencao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='processo',
            name='tag',
            field=models.CharField(blank=True, choices=[('reter', 'Impostos a Reter'), ('retidos', 'Impostos Retidos'), ('assinatura', 'Pendente Assinatura'), ('a_pagar', 'A Pagar'), ('pago', 'Pago')], max_length=50, null=True),
        ),
    ]
