# Generated by Django 6.0.2 on 2026-02-19 17:44

import django.db.models.deletion
import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_remove_notafiscal_entidade_imune_isenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='dados_retencao',
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.caminho_documento),
        ),
        migrations.CreateModel(
            name='RetencaoImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('6147', '6147 - Prestação de Serviços de Limpeza'), ('6190', '6190 - Serviços de Vigilância'), ('ISS', 'ISS - Imposto Sobre Serviços')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retencoes', to='processos.notafiscal')),
            ],
        ),
    ]
