# Generated by Django 6.0.2 on 2026-02-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_remove_notafiscal_dados_retencao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormasDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pagamento', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_choice', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_documento', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pagamento', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='retencaoimposto',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.codigosimposto'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.formasdepagamento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoices'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tagchoices'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdepagamento'),
        ),
    ]
