# Generated by Django 6.0.2 on 2026-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_codigosimposto_formasdepagamento_statuschoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credor',
            name='categoria',
            field=models.CharField(default='Credor X', max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credor',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa Física (CPF)'), ('PJ', 'Pessoa Jurídica (CNPJ)'), ('EX', 'Exterior / Outros')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
    ]
