# Generated by Django 6.0.2 on 2026-02-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_credor_categoria_alter_credor_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='path_process_folder',
        ),
    ]
