# Generated by Django 6.0.2 on 2026-03-01 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_remove_processo_path_process_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='ano_exercicio',
            field=models.IntegerField(blank=True, choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2026, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_empenho',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='extraorcamentario',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.formasdepagamento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoices'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.tagchoices'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdepagamento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
