# Generated by Django 6.0.2 on 2026-03-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_alter_processo_ano_exercicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDeCredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_de_credor', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContasDePagamentoOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_orgao', models.CharField(max_length=50, verbose_name='Banco do órgão')),
                ('agencia_orgao', models.CharField(max_length=50, verbose_name='Agência do órgão')),
                ('conta_orgao', models.CharField(max_length=50, verbose_name='Conta do órgão')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='credor',
            name='categoria',
        ),
        migrations.AddField(
            model_name='credor',
            name='agencia_credor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agência do credor'),
        ),
        migrations.AddField(
            model_name='credor',
            name='banco_credor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco do credor'),
        ),
        migrations.AddField(
            model_name='credor',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave PIX do credor'),
        ),
        migrations.AddField(
            model_name='credor',
            name='conta_credor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conta do credor'),
        ),
        migrations.AddField(
            model_name='credor',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email do credor'),
        ),
        migrations.AddField(
            model_name='credor',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone do credor'),
        ),
        migrations.AlterField(
            model_name='credor',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='credor',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='credor',
            name='categoria_credor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.categoriasdecredor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='conta_de_pagamento_orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.contasdepagamentoorgao'),
        ),
    ]
