# Generated by Django 6.0.2 on 2026-03-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_categoriasdecredor_contasdepagamentoorgao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='conta_de_pagamento_orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.contasdepagamentoorgao', verbose_name='Conta de Pagamento'),
        ),
    ]
