# Generated by Django 6.0.2 on 2026-03-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_alter_processo_conta_de_pagamento_orgao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeVerbasIndenizatorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_verba_indenizatoria', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='verba_indenizatoria',
            name='arquivo_pdf',
        ),
        migrations.AlterField(
            model_name='verba_indenizatoria',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdeverbasindenizatorias'),
        ),
    ]
