# Generated by Django 6.0.2 on 2026-03-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_tiposdeverbasindenizatorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='extraorcamentario',
        ),
        migrations.AddField(
            model_name='processo',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
