# Generated by Django 6.0.2 on 2026-03-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_remove_processo_extraorcamentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoicesPendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDePendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pendencia', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='StatusChoices',
            new_name='StatusChoicesProcesso',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='fiscal_contrato',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PF'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Beneficiário(a)'),
        ),
        migrations.AddField(
            model_name='verba_indenizatoria',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verbas_indenizatorias', to='processos.processo'),
        ),
        migrations.AlterField(
            model_name='verba_indenizatoria',
            name='beneficiario',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PF'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Beneficiário(a)'),
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='processos.processo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdependencias')),
            ],
        ),
    ]
