# Generated by Django 6.0.2 on 2026-03-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_statuschoicespendencias_tiposdependencias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoicesRetencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='codigosimposto',
            name='regra_competencia',
            field=models.CharField(choices=[('emissao', 'Pela Data de Emissão da NF'), ('pagamento', 'Pela Data de Pagamento')], default='emissao', max_length=15),
        ),
        migrations.AddField(
            model_name='retencaoimposto',
            name='competencia',
            field=models.DateField(blank=True, help_text='Salvo internamente como YYYY-MM-01, exibido como MM/AAAA', null=True, verbose_name='Mês de Competência'),
        ),
        migrations.AddField(
            model_name='retencaoimposto',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retencaoimposto',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoicesretencoes'),
        ),
    ]
