# Generated by Django 6.0.2 on 2026-03-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_statuschoicesretencoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=50, verbose_name='Agência')),
                ('conta', models.CharField(max_length=50, verbose_name='Conta')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processo',
            name='conta_de_pagamento_orgao',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='agencia_credor',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='banco_credor',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='conta_credor',
        ),
        migrations.AddField(
            model_name='credor',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.contasbancarias', verbose_name='Conta Credor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.contasbancarias', verbose_name='Conta Sacada'),
        ),
        migrations.DeleteModel(
            name='ContasDePagamentoOrgao',
        ),
    ]
