# Generated by Django 6.0.2 on 2026-03-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0016_contasbancarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprocesso',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Linha Digitável / Código de Barras'),
        ),
    ]
