# Generated by Django 6.0.2 on 2026-03-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0017_documentoprocesso_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='extraorcamentario',
            field=models.BooleanField(default=False, help_text='Marque se este processo não utiliza dotação orçamentária (ex: cauções).', verbose_name='Extraorçamentário'),
        ),
    ]
