# Generated by Django 6.0.2 on 2026-03-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0018_processo_extraorcamentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoprocesso',
            name='arquivo',
            field=models.FileField(upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='ordem',
            field=models.PositiveIntegerField(default=1, help_text='Ordem do arquivo'),
        ),
        migrations.CreateModel(
            name='DocumentoVerba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento')),
                ('verba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.verba_indenizatoria')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
            },
        ),
    ]
