# Generated by Django 6.0.2 on 2026-03-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_alter_documentoprocesso_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verba_indenizatoria',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
