# Generated by Django 6.0.2 on 2026-03-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_verba_indenizatoria_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CategoriasDeCredor',
            new_name='CargosFuncoes',
        ),
        migrations.RenameField(
            model_name='cargosfuncoes',
            old_name='categoria_de_credor',
            new_name='cargo_funcao',
        ),
        migrations.RenameField(
            model_name='credor',
            old_name='categoria_credor',
            new_name='cargo_funcao',
        ),
        migrations.AddField(
            model_name='retencaoimposto',
            name='rendimento_tributavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='credor',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.grupos'),
        ),
    ]
