# Generated by Django 6.0.2 on 2026-03-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_grupos_rename_categoriasdecredor_cargosfuncoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_Valores_Unitarios_Verbas_Indenizatorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cargo_funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.cargosfuncoes')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdeverbasindenizatorias')),
            ],
        ),
        migrations.CreateModel(
            name='Tabela_Proponentes_Diarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios_mapeados', to='processos.cargosfuncoes', verbose_name='Cargo do Beneficiário')),
                ('proponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proponentes_mapeados', to='processos.cargosfuncoes', verbose_name='Cargo do Proponente (Aprovador)')),
            ],
            options={
                'unique_together': {('cargo_funcao', 'proponente')},
            },
        ),
    ]
