# Generated by Django 6.0.2 on 2026-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0022_tabela_valores_unitarios_verbas_indenizatorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasbancarias',
            name='titular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='agencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='conta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conta'),
        ),
    ]
