# Generated by Django 6.0.2 on 2026-03-07 09:09

import django.db.models.deletion
import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_contasbancarias_titular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoicesVerbasIndenizatorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='verba_indenizatoria',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='verba_indenizatoria',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='verba_indenizatoria',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.caminho_documento),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de Barras'),
        ),
        migrations.CreateModel(
            name='AuxilioRepresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.CharField(max_length=50, verbose_name='Número Sequencial')),
                ('objetivo', models.CharField(blank=True, help_text='Preencha se for representação em evento específico', max_length=200, null=True, verbose_name='Evento/Motivo da Representação')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('beneficiario', models.ForeignKey(limit_choices_to={'tipo': 'PF'}, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Beneficiário')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auxilios_representacao', to='processos.processo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoicesverbasindenizatorias')),
            ],
        ),
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.CharField(max_length=50, verbose_name='Número Sequencial')),
                ('tipo_solicitacao', models.CharField(choices=[('INICIAL', 'Concessão Inicial'), ('PRORROGACAO', 'Prorrogação'), ('COMPLEMENTACAO', 'Complementação')], default='INICIAL', max_length=20)),
                ('data_saida', models.DateField(verbose_name='Data de Saída')),
                ('data_retorno', models.DateField(verbose_name='Data de Retorno')),
                ('cidade_origem', models.CharField(max_length=50, verbose_name='Cidade de Origem')),
                ('cidade_destino', models.CharField(max_length=100, verbose_name='Cidade(s) de Destino')),
                ('objetivo', models.CharField(max_length=200, verbose_name='Objetivo da Viagem')),
                ('quantidade_diarias', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Quantidade de Diárias')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('beneficiario', models.ForeignKey(limit_choices_to={'tipo': 'PF'}, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Beneficiário')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diarias', to='processos.processo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoicesverbasindenizatorias')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAuxilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=processos.models.caminho_documento)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo')),
                ('auxilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.auxiliorepresentacao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=processos.models.caminho_documento)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo')),
                ('diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.diaria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.CharField(max_length=50, verbose_name='Número Sequencial')),
                ('reuniao', models.CharField(max_length=7, verbose_name='Reunião/Sessão de Referência')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('beneficiario', models.ForeignKey(limit_choices_to={'tipo': 'PF'}, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Conselheiro(a)')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='processos.processo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoicesverbasindenizatorias')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoJeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=processos.models.caminho_documento)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento')),
                ('jeton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.jeton')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReembolsoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.CharField(max_length=50, verbose_name='Número Sequencial')),
                ('data_saida', models.DateField(verbose_name='Data de Saída')),
                ('data_retorno', models.DateField(verbose_name='Data de Retorno')),
                ('cidade_origem', models.CharField(max_length=50, verbose_name='Cidade de Origem')),
                ('cidade_destino', models.CharField(max_length=100, verbose_name='Cidade(s) de Destino')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distância Percorrida (KM)')),
                ('preco_combustivel', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço Médio do Combustível (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Reembolso (R$)')),
                ('objetivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Objetivo')),
                ('beneficiario', models.ForeignKey(limit_choices_to={'tipo': 'PF'}, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Beneficiário')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos_combustivel', to='processos.processo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoicesverbasindenizatorias')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=processos.models.caminho_documento)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento')),
                ('reembolso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.reembolsocombustivel')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DocumentoVerba',
        ),
        migrations.DeleteModel(
            name='Verba_Indenizatoria',
        ),
    ]
