# Generated by Django 6.0.2 on 2026-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0024_statuschoicesverbasindenizatorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosimposto',
            name='aliquota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='codigosimposto',
            name='vencimento_padrao',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Dia de Vencimento Padrão', null=True),
        ),
        migrations.AlterField(
            model_name='codigosimposto',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
