# Generated by Django 6.0.2 on 2026-03-08 20:15

import django.db.models.deletion
import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0025_codigosimposto_aliquota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoicesSuprimentoDeFundos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuprimentoDeFundos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Numerário Liberado (R$)')),
                ('taxa_saque', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor da Taxa de Saque (R$)')),
                ('lotacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lotação')),
                ('data_saida', models.DateField(verbose_name='Período Inicial (De)')),
                ('data_retorno', models.DateField(verbose_name='Período Final (Ate)')),
                ('data_recibo', models.DateField(blank=True, null=True, verbose_name='Data de Carga na Conta')),
                ('data_devolucao_saldo', models.DateField(blank=True, null=True, verbose_name='Data de Devolução de Saldo Remanescente')),
                ('valor_devolvido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Devolvido (R$)')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suprimentos', to='processos.processo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.statuschoicessuprimentodefundos')),
                ('suprido', models.ForeignKey(limit_choices_to={'tipo': 'PF'}, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Suprido')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSuprimentoDeFundos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=processos.models.caminho_documento)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem do arquivo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tiposdedocumento')),
                ('suprimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.suprimentodefundos')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespesaSuprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Compra')),
                ('estabelecimento', models.CharField(max_length=150, verbose_name='Estabelecimento (Credor)')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('detalhamento', models.CharField(max_length=255, verbose_name='Material/Serviço Adquirido')),
                ('nota_fiscal', models.CharField(max_length=50, verbose_name='Nº Nota Fiscal/Cupom')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('suprimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='processos.suprimentodefundos')),
            ],
        ),
    ]
