# Generated by Django 6.0.2 on 2026-03-08 20:53

import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0026_statuschoicessuprimentodefundos_suprimentodefundos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesasuprimento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=processos.models.caminho_documento, verbose_name='Arquivo Único (Solicitação + NF)'),
        ),
    ]
