# Generated by Django 6.0.3 on 2026-03-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0027_despesasuprimento_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="credor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processos.credor",
            ),
        ),
    ]
