# Generated by Django 6.0.3 on 2026-03-10 17:28

import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0028_alter_processo_credor"),
    ]

    operations = [
        migrations.AddField(
            model_name="notafiscal",
            name="arquivo",
            field=models.FileField(
                blank=True, null=True, upload_to=processos.models.caminho_documento
            ),
        ),
    ]
