# Generated by Django 6.0.3 on 2026-03-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0029_notafiscal_arquivo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargosfuncoes",
            options={
                "verbose_name": "Cargo / Função",
                "verbose_name_plural": "Cargos e Funções",
            },
        ),
        migrations.AddField(
            model_name="cargosfuncoes",
            name="grupo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cargos",
                to="processos.grupos",
                verbose_name="Grupo Relacionado",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cargosfuncoes",
            name="cargo_funcao",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="cargosfuncoes",
            unique_together={("grupo", "cargo_funcao")},
        ),
    ]
