# Generated by Django 6.0.3 on 2026-03-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0030_alter_cargosfuncoes_options_cargosfuncoes_grupo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscal",
            name="cnpj_emitente",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="fiscal_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "PF"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscalizadas",
                to="processos.credor",
                verbose_name="Fiscal do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="nome_emitente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processos.credor",
            ),
        ),
    ]
