# Generated by Django 6.0.3 on 2026-03-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0031_alter_notafiscal_cnpj_emitente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="arquivo_final",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="processos_arquivados/",
                verbose_name="Processo Consolidado",
            ),
        ),
    ]
