# Generated by Django 6.0.3 on 2026-03-11 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0032_processo_arquivo_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiposdedocumento",
            name="tipo_de_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processos.tiposdepagamento",
            ),
        ),
    ]
