# Generated by Django 6.0.3 on 2026-03-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0033_tiposdedocumento_tipo_de_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendencia",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processos.statuschoicespendencias",
            ),
        ),
    ]
