# Generated by Django 6.0.3 on 2026-03-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0034_pendencia_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notafiscal",
            name="atestada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="fiscal_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo": "FUNCIONÁRIOS"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscalizadas",
                to="processos.credor",
                verbose_name="Fiscal do Contrato",
            ),
        ),
    ]
