# Generated by Django 6.0.3 on 2026-03-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0035_notafiscal_atestada_alter_notafiscal_fiscal_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscal",
            name="fiscal_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"grupo__grupo": "FUNCIONÁRIOS"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscalizadas",
                to="processos.credor",
                verbose_name="Fiscal do Contrato",
            ),
        ),
    ]
