# Generated by Django 6.0.3 on 2026-03-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0036_alter_notafiscal_fiscal_contrato"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notafiscal",
            name="arquivo",
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="documento_vinculado",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nota_referente",
                to="processos.documentoprocesso",
                verbose_name="Documento PDF da Nota",
            ),
        ),
    ]
