# Generated by Django 6.0.3 on 2026-03-13 13:23

import django.db.models.deletion
import processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0037_remove_notafiscal_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago')),
                ('tipo_de_pagamento', models.CharField(blank=True, choices=[('GERENCIADOR', 'GERENCIADOR/BOLETO BANCÁRIO'), ('TED', 'TRANSFERÊNCIA (TED)'), ('PIX', 'PIX'), ('REMESSA', 'REMESSA BANCÁRIA')], max_length=50, null=True, verbose_name='Tipo de Pagamento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=processos.models.caminho_comprovante, verbose_name='Arquivo do Comprovante')),
                ('credor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Credor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_pagamento', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Comprovante de Pagamento',
                'verbose_name_plural': 'Comprovantes de Pagamento',
            },
        ),
    ]
