# Generated by Django 6.0.3 on 2026-03-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0038_add_comprovante_de_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprovantedepagamento',
            name='credor',
        ),
        migrations.AddField(
            model_name='comprovantedepagamento',
            name='credor_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Credor (Texto)'),
        ),
    ]
