# Generated by Django 6.0.3 on 2026-03-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0039_replace_comprovante_credor_fk_with_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total (R$)'),
        ),
    ]
