# Generated by Django 6.0.3 on 2026-03-15 20:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0041_historicaldocumentoauxilio_historicaldocumentodiaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='em_contingencia',
            field=models.BooleanField(default=False, help_text='Indica que existe uma Contingência ativa para este processo. Nenhuma operação financeira pode ser realizada enquanto este flag estiver ativo.', verbose_name='Em Contingência'),
        ),
        migrations.AddField(
            model_name='processo',
            name='em_contingencia',
            field=models.BooleanField(default=False, help_text='Indica que existe uma Contingência ativa para este processo. Nenhuma operação financeira pode ser realizada enquanto este flag estiver ativo.', verbose_name='Em Contingência'),
        ),
        migrations.CreateModel(
            name='Contingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField(help_text='Motivo detalhado para a quebra de fluxo/retificação.')),
                ('dados_propostos', models.JSONField(default=dict, help_text="Dicionário JSON contendo o estado exato dos campos que serão alterados no Processo (ex: {'credor_id': 5}).")),
                ('status', models.CharField(choices=[('PENDENTE_SUPERVISOR', 'Pendente Supervisor'), ('PENDENTE_ORDENADOR', 'Pendente Ordenador de Despesa'), ('PENDENTE_CONSELHO', 'Pendente Conselho Fiscal'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE_SUPERVISOR', max_length=30)),
                ('parecer_supervisor', models.TextField(blank=True, null=True)),
                ('data_aprovacao_supervisor', models.DateTimeField(blank=True, null=True)),
                ('parecer_ordenador', models.TextField(blank=True, null=True)),
                ('data_aprovacao_ordenador', models.DateTimeField(blank=True, null=True)),
                ('parecer_conselho', models.TextField(blank=True, null=True)),
                ('data_aprovacao_conselho', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por_conselho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cont_conselho', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por_ordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cont_ordenadas', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cont_supervisionadas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingencias', to='processos.processo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contingencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contingência',
                'verbose_name_plural': 'Contingências',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContingencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(blank=True, editable=False)),
                ('justificativa', models.TextField(help_text='Motivo detalhado para a quebra de fluxo/retificação.')),
                ('dados_propostos', models.JSONField(default=dict, help_text="Dicionário JSON contendo o estado exato dos campos que serão alterados no Processo (ex: {'credor_id': 5}).")),
                ('status', models.CharField(choices=[('PENDENTE_SUPERVISOR', 'Pendente Supervisor'), ('PENDENTE_ORDENADOR', 'Pendente Ordenador de Despesa'), ('PENDENTE_CONSELHO', 'Pendente Conselho Fiscal'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE_SUPERVISOR', max_length=30)),
                ('parecer_supervisor', models.TextField(blank=True, null=True)),
                ('data_aprovacao_supervisor', models.DateTimeField(blank=True, null=True)),
                ('parecer_ordenador', models.TextField(blank=True, null=True)),
                ('data_aprovacao_ordenador', models.DateTimeField(blank=True, null=True)),
                ('parecer_conselho', models.TextField(blank=True, null=True)),
                ('data_aprovacao_conselho', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprovado_por_conselho', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por_ordenador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('aprovado_por_supervisor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo')),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contingência',
                'verbose_name_plural': 'historical Contingências',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
