# Generated by Django 6.0.3 on 2026-03-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0042_add_contingencia_model_and_em_contingencia_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencaoimposto',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retencoes', to='processos.credor', verbose_name='Beneficiário'),
        ),
    ]
