# Generated by Django 6.0.3 on 2026-03-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0043_add_beneficiario_to_retencaoimposto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeiosDeTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_de_transporte', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='diaria',
            name='meio_de_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.meiosdetransporte', verbose_name='Meio de Transporte'),
        ),
    ]
