# Generated by Django 6.0.3 on 2026-03-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0044_meiosdetransporte_diaria_meio_de_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolsocombustivel',
            name='diaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos_combustivel', to='processos.diaria', verbose_name='Diária'),
        ),
    ]
