# Generated by Django 6.0.3 on 2026-03-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0045_add_diaria_fk_to_reembolsocombustivel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotaFiscal',
            new_name='DocumentoFiscal',
        ),
    ]
