# Generated by Django 6.0.3 on 2026-03-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0046_rename_notafiscal_to_documentofiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='proponente',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PF'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarias_como_proponente', to='processos.credor', verbose_name='Proponente'),
        ),
        migrations.AlterField(
            model_name='diaria',
            name='beneficiario',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PF'}, on_delete=django.db.models.deletion.PROTECT, related_name='diarias_como_beneficiario', to='processos.credor', verbose_name='Beneficiário'),
        ),
    ]
