# Generated by Django 6.0.3 on 2026-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0049_historicalauxiliorepresentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosimposto',
            name='natureza_rendimento',
            field=models.CharField(blank=True, help_text='Código de 5 dígitos (Tabela 01 do SPED). Ex: 15001, 17001. Mapeia o código de receita para o XML.', max_length=5, null=True, verbose_name='Natureza do Rendimento (EFD-Reinf)'),
        ),
        migrations.AddField(
            model_name='credor',
            name='codigo_servico_padrao',
            field=models.CharField(blank=True, help_text='Ex: 100000001 (Limpeza). Será herdado automaticamente pelas Notas Fiscais deste credor.', max_length=9, null=True, verbose_name='Cód. Serviço Padrão INSS (Tabela 06)'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='codigo_servico_inss',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Cód. Serviço INSS (Tabela 06 Reinf)'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='serie_nota_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='historicalcredor',
            name='codigo_servico_padrao',
            field=models.CharField(blank=True, help_text='Ex: 100000001 (Limpeza). Será herdado automaticamente pelas Notas Fiscais deste credor.', max_length=9, null=True, verbose_name='Cód. Serviço Padrão INSS (Tabela 06)'),
        ),
        migrations.AddField(
            model_name='historicaldocumentofiscal',
            name='codigo_servico_inss',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Cód. Serviço INSS (Tabela 06 Reinf)'),
        ),
        migrations.AddField(
            model_name='historicaldocumentofiscal',
            name='serie_nota_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
    ]
