# Generated by Django 6.0.3 on 2026-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0050_add_reinf_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprovantedepagamento',
            name='tipo_de_pagamento',
        ),
        migrations.RemoveField(
            model_name='historicalcomprovantedepagamento',
            name='tipo_de_pagamento',
        ),
        migrations.AddField(
            model_name='comprovantedepagamento',
            name='numero_comprovante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Comprovante'),
        ),
        migrations.AddField(
            model_name='historicalcomprovantedepagamento',
            name='numero_comprovante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Comprovante'),
        ),
    ]
