# Generated by Django 6.0.3 on 2026-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0051_comprovante_remove_tipo_add_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprocesso',
            name='imutavel',
            field=models.BooleanField(default=False, help_text='Documento bloqueado para exclusão. Definido automaticamente durante a etapa de Conferência.', verbose_name='Imutável'),
        ),
        migrations.AddField(
            model_name='historicaldocumentoprocesso',
            name='imutavel',
            field=models.BooleanField(default=False, help_text='Documento bloqueado para exclusão. Definido automaticamente durante a etapa de Conferência.', verbose_name='Imutável'),
        ),
    ]
