# Generated by Django 6.0.3 on 2026-03-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0052_add_imutavel_to_documentoprocesso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'permissions': [('acesso_backoffice', 'Pode acessar as telas gerais do sistema financeiro'), ('pode_operar_contas_pagar', 'Pode empenhar, triar notas e fazer conferência'), ('pode_atestar_liquidacao', 'Pode atestar notas fiscais (Fiscal do Contrato)'), ('pode_autorizar_pagamento', 'Pode autorizar pagamentos (Ordenador)'), ('pode_contabilizar', 'Pode registrar a contabilização (Contador)'), ('pode_auditar_conselho', 'Pode aprovar no Conselho Fiscal')]},
        ),
    ]
