# Generated by Django 6.0.3 on 2026-03-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0053_add_rbac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosimposto',
            name='familia',
            field=models.CharField(blank=True, choices=[('INSS', 'Previdenciário (Série 2000)'), ('FEDERAL', 'Federal - IR/CSRF (Série 4000)')], default='FEDERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalretencaoimposto',
            name='rendimento_tributavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Base de Cálculo / Rend. Tributável'),
        ),
        migrations.AlterField(
            model_name='historicalretencaoimposto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Retido'),
        ),
        migrations.AlterField(
            model_name='retencaoimposto',
            name='rendimento_tributavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Base de Cálculo / Rend. Tributável'),
        ),
        migrations.AlterField(
            model_name='retencaoimposto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Retido'),
        ),
    ]
