# Generated by Django 6.0.3 on 2026-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0053_add_rbac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosimposto',
            name='serie_reinf',
            field=models.CharField(choices=[('NONE', 'Não mapeado'), ('S2000', 'Série 2000 – Previdenciário (INSS)'), ('S4000', 'Série 4000 – Retenções Federais (IRRF/CSRF)')], default='NONE', help_text='Classifica o imposto para geração do XML EFD-Reinf: S2000 = INSS, S4000 = IR/CSLL/PIS/COFINS.', max_length=6, verbose_name='Série EFD-Reinf'),
        ),
    ]
