# Generated by Django 6.0.3 on 2026-03-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0054_add_serie_reinf_to_codigosimposto'),
        ('processos', '0054_fix_retencaoimposto_fields_add_familia_to_codigosimposto'),
    ]

    operations = [
    ]
