# Generated by Django 6.0.3 on 2026-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0055_merge_20260318_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosContribuinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=255)),
                ('tipo_inscricao', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Dados do Contribuinte',
                'verbose_name_plural': 'Dados do Contribuinte',
            },
        ),
    ]
