# Generated by Django 6.0.3 on 2026-03-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0056_add_dadoscontribuinte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigosimposto',
            name='familia',
        ),
    ]
