# Generated by Django 6.0.3 on 2026-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0057_remove_familia_from_codigosimposto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='codigo_barras',
        ),
    ]
