# Generated by Django 6.0.3 on 2026-03-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0057_remove_familia_from_codigosimposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasbancarias',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='processos.credor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_sacados', to='processos.contasbancarias', verbose_name='Conta Sacada'),
        ),
    ]
