# Generated by Django 6.0.3 on 2026-03-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0058_conta_sacada_cnpj_filter'),
        ('processos', '0058_remove_codigo_barras_from_processo'),
    ]

    operations = [
    ]
