# Generated by Django 6.0.3 on 2026-03-20 03:15

import django.db.models.deletion
import processos.models.fiscal
import processos.models.fluxo
import processos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0061_add_pode_arquivar_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroacessoarquivo',
            options={'ordering': ['-data_acesso'], 'verbose_name': 'Registro de Acesso a Arquivo', 'verbose_name_plural': 'Registros de Acesso a Arquivos'},
        ),
        migrations.AlterField(
            model_name='comprovantedepagamento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=processos.models.fiscal.caminho_comprovante, validators=[processos.validators.validar_arquivo_seguro], verbose_name='Arquivo do Comprovante'),
        ),
        migrations.AlterField(
            model_name='despesasuprimento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro], verbose_name='Arquivo Único (Solicitação + NF)'),
        ),
        migrations.AlterField(
            model_name='documentoauxilio',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='documentodiaria',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='documentojeton',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='documentoreembolso',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='documentosuprimentodefundos',
            name='arquivo',
            field=models.FileField(upload_to=processos.models.fluxo.caminho_documento, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicalcomprovantedepagamento',
            name='arquivo',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[processos.validators.validar_arquivo_seguro], verbose_name='Arquivo do Comprovante'),
        ),
        migrations.AlterField(
            model_name='historicaldespesasuprimento',
            name='arquivo',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[processos.validators.validar_arquivo_seguro], verbose_name='Arquivo Único (Solicitação + NF)'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentoauxilio',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicaldocumentodiaria',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicaldocumentojeton',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicaldocumentoprocesso',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicaldocumentoreembolso',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicaldocumentosuprimentodefundos',
            name='arquivo',
            field=models.TextField(max_length=100, validators=[processos.validators.validar_arquivo_seguro]),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='arquivo_final',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[processos.validators.validar_arquivo_seguro], verbose_name='Processo Consolidado'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='arquivo_final',
            field=models.FileField(blank=True, null=True, upload_to='processos_arquivados/', validators=[processos.validators.validar_arquivo_seguro], verbose_name='Processo Consolidado'),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_devolvido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_devolucao', models.DateField()),
                ('motivo', models.TextField()),
                ('comprovante', models.FileField(help_text='Comprovante de depósito/GRU', upload_to='devolucoes/', validators=[processos.validators.validar_arquivo_seguro])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-data_devolucao'],
            },
        ),
    ]
