# Generated by Django 6.0.3 on 2026-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0062_add_devolucao_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='numero_siscac',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nº SISCAC'),
        ),
        migrations.AddField(
            model_name='historicaldiaria',
            name='numero_siscac',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Nº SISCAC'),
        ),
    ]
