# Generated by Django 6.0.3 on 2026-03-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0064_remove_numero_sequencial_from_diaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='fiscal_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal do Contrato'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentofiscal',
            name='fiscal_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal do Contrato'),
        ),
    ]
