# Generated by Django 6.0.3 on 2026-03-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0065_alter_documentofiscal_fiscal_contrato_to_user'),
        ('processos', '0065_diaria_proponente_user_fk'),
    ]

    operations = [
    ]
