# Generated by Django 6.0.3 on 2026-03-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0066_merge_20260321_1810'),
        ('processos', '0066_merge_20260321_1811'),
    ]

    operations = [
    ]
