# Generated by Django 6.0.3 on 2026-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0067_merge_20260322_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='arquivo_assinado',
            field=models.FileField(blank=True, null=True, upload_to='verbasindenizatorias/diarias/assinadas/', verbose_name='PCD Assinada'),
        ),
        migrations.AddField(
            model_name='diaria',
            name='autentique_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Autentique'),
        ),
        migrations.AddField(
            model_name='diaria',
            name='autentique_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Autentique'),
        ),
        migrations.AddField(
            model_name='diaria',
            name='status_assinatura',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente de Assinatura'), ('ASSINADO', 'Assinado')], max_length=20, null=True, verbose_name='Status de Assinatura'),
        ),
        migrations.AddField(
            model_name='historicaldiaria',
            name='arquivo_assinado',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='PCD Assinada'),
        ),
        migrations.AddField(
            model_name='historicaldiaria',
            name='autentique_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Autentique'),
        ),
        migrations.AddField(
            model_name='historicaldiaria',
            name='autentique_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Autentique'),
        ),
        migrations.AddField(
            model_name='historicaldiaria',
            name='status_assinatura',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente de Assinatura'), ('ASSINADO', 'Assinado')], max_length=20, null=True, verbose_name='Status de Assinatura'),
        ),
    ]
