# Generated by Django 6.0.3 on 2026-03-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0068_add_autentique_fields_to_diaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Ex: Conta de Luz - Sede', max_length=200, verbose_name='Referência / Descrição')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia Padrão de Vencimento')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.credor', verbose_name='Credor/Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta Fixa',
                'verbose_name_plural': 'Contas Fixas',
            },
        ),
        migrations.CreateModel(
            name='FaturaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('conta_fixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='processos.contafixa')),
                ('processo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_vinculadas', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Fatura Mensal',
                'verbose_name_plural': 'Faturas Mensais',
                'unique_together': {('conta_fixa', 'mes_referencia')},
            },
        ),
    ]
