# Generated by Django 6.0.3 on 2026-03-23 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0069_contafixa_faturamensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contafixa',
            name='dia_vencimento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia Padrão de Vencimento'),
        ),
    ]
