# Generated by Django 6.0.3 on 2026-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0070_alter_contafixa_dia_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcredor',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='cargosfuncoes',
            name='grupo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Grupo Relacionado'),
        ),
        migrations.RemoveField(
            model_name='codigosimposto',
            name='vencimento_padrao',
        ),
        migrations.DeleteModel(
            name='Grupos',
        ),
    ]
