# Generated by Django 6.0.3 on 2026-03-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0071_remove_grupos_model_and_credor_grupo_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Ex: 16 para a 16ª Reunião', verbose_name='Número da Reunião')),
                ('data_reuniao', models.DateField(blank=True, null=True, verbose_name='Data da Reunião')),
                ('trimestre_referencia', models.CharField(help_text='Ex: 1º Trimestre / 2026', max_length=50, verbose_name='Trimestre/Ano de Referência')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada/Em Montagem'), ('EM_ANALISE', 'Em Análise pelo Conselho'), ('CONCLUIDA', 'Concluída')], default='AGENDADA', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Reunião do Conselho',
                'verbose_name_plural': 'Reuniões do Conselho',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='reuniao_conselho',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.reuniaoconselho', verbose_name='Reunião do Conselho'),
        ),
        migrations.AddField(
            model_name='processo',
            name='reuniao_conselho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_em_pauta', to='processos.reuniaoconselho', verbose_name='Reunião do Conselho'),
        ),
    ]
