# Generated by Django 6.0.3 on 2026-03-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('processos', '0072_add_reuniao_conselho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigosimposto',
            name='vencimento_padrao',
        ),
        migrations.RemoveField(
            model_name='diaria',
            name='arquivo_assinado',
        ),
        migrations.RemoveField(
            model_name='diaria',
            name='autentique_id',
        ),
        migrations.RemoveField(
            model_name='diaria',
            name='autentique_url',
        ),
        migrations.RemoveField(
            model_name='diaria',
            name='status_assinatura',
        ),
        migrations.RemoveField(
            model_name='historicaldiaria',
            name='arquivo_assinado',
        ),
        migrations.RemoveField(
            model_name='historicaldiaria',
            name='autentique_id',
        ),
        migrations.RemoveField(
            model_name='historicaldiaria',
            name='autentique_url',
        ),
        migrations.RemoveField(
            model_name='historicaldiaria',
            name='status_assinatura',
        ),
        migrations.CreateModel(
            name='AssinaturaAutentique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo_documento', models.CharField(help_text='Ex: SCD, PCD, AUTORIZACAO', max_length=50, verbose_name='Tipo do Documento')),
                ('autentique_id', models.CharField(max_length=100, unique=True, verbose_name='ID Autentique')),
                ('autentique_url', models.URLField(max_length=500, verbose_name='URL para Assinatura')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='documentos_assinados/', verbose_name='Arquivo Assinado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
