# Generated by Django 6.0.3 on 2026-03-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0073_add_assinatura_autentique_and_remove_diaria_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalretencaoimposto',
            name='processo_pagamento',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='O Processo agrupado gerado para pagar esta retenção ao órgão arrecadador.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo', verbose_name='Processo de Recolhimento'),
        ),
        migrations.AddField(
            model_name='retencaoimposto',
            name='processo_pagamento',
            field=models.ForeignKey(blank=True, help_text='O Processo agrupado gerado para pagar esta retenção ao órgão arrecadador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impostos_recolhidos', to='processos.processo', verbose_name='Processo de Recolhimento'),
        ),
    ]
