# Generated by Django 6.0.3 on 2026-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0074_add_processo_pagamento_to_retencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdedocumento',
            name='tipo_de_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tiposdedocumento',
            constraint=models.UniqueConstraint(fields=('tipo_de_documento', 'tipo_de_pagamento'), name='unique_documento_por_pagamento'),
        ),
    ]
