# Generated by Django 6.0.3 on 2026-03-29 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0075_refactor_tipos_documento_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaautentique',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assinaturaautentique',
            name='dados_signatarios',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados dos Signatários'),
        ),
        migrations.AlterField(
            model_name='assinaturaautentique',
            name='autentique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Autentique'),
        ),
        migrations.AlterField(
            model_name='assinaturaautentique',
            name='autentique_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL para Assinatura'),
        ),
        migrations.AlterField(
            model_name='assinaturaautentique',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado'), ('REJEITADO', 'Rejeitado'), ('ERRO', 'Erro')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
