# Generated by Django 6.0.3 on 2026-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0076_assinaturaautentique_criador_dados_signatarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaautentique',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='assinaturas_rascunho/', verbose_name='Arquivo (Rascunho)'),
        ),
    ]
