# Generated by Django 6.0.3 on 2026-03-30 20:24

import datetime
from django.db import migrations, models

# Original default used when this field was first introduced in migration 0025.
VENCIMENTO_PADRAO_DEFAULT = 1

# Allowed table names to guard the PRAGMA introspection helper.
_ALLOWED_TABLES = frozenset([
    'processos_codigosimposto',
    'processos_contafixa',
])


def column_exists(cursor, table, column):
    """Return True if *column* exists in *table* for the active database vendor.

    Only tables present in _ALLOWED_TABLES are accepted to prevent any
    accidental misuse of the PRAGMA-based introspection path.
    """
    if table not in _ALLOWED_TABLES:
        raise ValueError(f"Table '{table}' is not in the allowed introspection list.")
    vendor = cursor.db.vendor
    if vendor == 'sqlite':
        # PRAGMA does not support parameter binding for table names; the
        # allowlist check above ensures no untrusted input reaches this path.
        cursor.execute(f"PRAGMA table_info({table})")
        return any(row[1] == column for row in cursor.fetchall())
    else:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns"
            " WHERE table_name = %s AND column_name = %s",
            [table, column],
        )
        return cursor.fetchone() is not None


def remove_vencimento_padrao(apps, schema_editor):
    """Remove vencimento_padrao from codigosimposto only if the column exists."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if not column_exists(cursor, 'processos_codigosimposto', 'vencimento_padrao'):
            return
        if vendor == 'sqlite':
            cursor.execute(
                "ALTER TABLE processos_codigosimposto DROP COLUMN vencimento_padrao"
            )
        else:
            cursor.execute(
                "ALTER TABLE processos_codigosimposto DROP COLUMN IF EXISTS vencimento_padrao"
            )


def restore_vencimento_padrao(apps, schema_editor):
    """Reverse: re-add vencimento_padrao to codigosimposto if absent."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if column_exists(cursor, 'processos_codigosimposto', 'vencimento_padrao'):
            return
        if vendor == 'sqlite':
            cursor.execute(
                "ALTER TABLE processos_codigosimposto"
                " ADD COLUMN vencimento_padrao integer NULL DEFAULT %d" % VENCIMENTO_PADRAO_DEFAULT
            )
        else:
            cursor.execute(
                "ALTER TABLE processos_codigosimposto"
                " ADD COLUMN IF NOT EXISTS vencimento_padrao integer NULL DEFAULT %s",
                [VENCIMENTO_PADRAO_DEFAULT],
            )


def add_data_inicio(apps, schema_editor):
    """Add data_inicio to contafixa only if the column does not already exist."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if column_exists(cursor, 'processos_contafixa', 'data_inicio'):
            return
        if vendor == 'sqlite':
            # ALTER TABLE … ADD COLUMN accepts CURRENT_DATE as a constant default.
            cursor.execute(
                "ALTER TABLE processos_contafixa"
                " ADD COLUMN data_inicio date NOT NULL DEFAULT CURRENT_DATE"
            )
        else:
            cursor.execute(
                "ALTER TABLE processos_contafixa"
                " ADD COLUMN IF NOT EXISTS data_inicio date NOT NULL DEFAULT CURRENT_DATE"
            )


def remove_data_inicio(apps, schema_editor):
    """Reverse: remove data_inicio from contafixa if present."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if not column_exists(cursor, 'processos_contafixa', 'data_inicio'):
            return
        if vendor == 'sqlite':
            cursor.execute(
                "ALTER TABLE processos_contafixa DROP COLUMN data_inicio"
            )
        else:
            cursor.execute(
                "ALTER TABLE processos_contafixa DROP COLUMN IF EXISTS data_inicio"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0077_assinaturaautentique_arquivo'),
    ]

    operations = [
        # RunPython handles edge cases where columns may already have been
        # added/removed manually (e.g. by a prior developer intervention).
        migrations.RunPython(remove_vencimento_padrao, reverse_code=restore_vencimento_padrao),
        migrations.RunPython(add_data_inicio, reverse_code=remove_data_inicio),
        # Update Django's internal migration state without touching the DB
        # (the actual DDL was already executed by the RunPython steps above).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='codigosimposto',
                    name='vencimento_padrao',
                ),
                migrations.AddField(
                    model_name='contafixa',
                    name='data_inicio',
                    field=models.DateField(
                        default=datetime.date.today,
                        help_text='Mês a partir do qual as faturas mensais serão geradas.',
                        verbose_name='Data de Início',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
