# Generated by Django 6.0.3 on 2026-03-30 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0077_assinaturaautentique_arquivo'),
    ]
        migrations.AddField(
            model_name='contafixa',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, help_text='Mês a partir do qual as faturas mensais serão geradas.', verbose_name='Data de Início'),
        ),
    ]
