# Generated by Django 6.0.3 on 2026-04-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0079_add_verbas_rbac_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processo",
            options={
                "permissions": [
                    ("acesso_backoffice", "Pode acessar as telas gerais do sistema financeiro"),
                    ("pode_operar_contas_pagar", "Pode empenhar, triar notas e fazer conferência"),
                    ("pode_aprovar_contingencia_supervisor", "Pode aprovar contingências na etapa de supervisão/gerência"),
                    ("pode_atestar_liquidacao", "Pode atestar notas fiscais (Fiscal do Contrato)"),
                    ("pode_autorizar_pagamento", "Pode autorizar pagamentos (Ordenador)"),
                    ("pode_contabilizar", "Pode registrar a contabilização (Contador)"),
                    ("pode_auditar_conselho", "Pode aprovar no Conselho Fiscal"),
                    ("pode_arquivar", "Pode realizar o arquivamento definitivo de processos"),
                    ("pode_visualizar_verbas", "Pode visualizar painéis e listas de verbas indenizatórias"),
                    ("pode_criar_diarias", "Pode cadastrar solicitações de diárias"),
                    ("pode_importar_diarias", "Pode importar diárias em lote"),
                    ("pode_gerenciar_diarias", "Pode editar diárias e seus documentos"),
                    ("pode_autorizar_diarias", "Pode autorizar e aprovar diárias"),
                    ("pode_gerenciar_reembolsos", "Pode cadastrar e editar reembolsos de combustível"),
                    ("pode_gerenciar_jetons", "Pode cadastrar e editar jetons"),
                    ("pode_gerenciar_auxilios", "Pode cadastrar e editar auxílios representação"),
                    ("pode_agrupar_verbas", "Pode agrupar verbas em processos de pagamento"),
                    ("pode_gerenciar_processos_verbas", "Pode editar processos originados de verbas indenizatórias"),
                    ("pode_sincronizar_diarias_siscac", "Pode sincronizar/importar diárias via SISCAC"),
                ],
            },
        ),
        migrations.AddField(
            model_name="contingencia",
            name="data_revisao_contadora",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contingencia",
            name="exige_aprovacao_conselho",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contingencia",
            name="exige_aprovacao_ordenador",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contingencia",
            name="exige_revisao_contadora",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contingencia",
            name="parecer_contadora",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contingencia",
            name="revisado_por_contadora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cont_revisadas_contadora",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contingencia",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE_SUPERVISOR", "Pendente Supervisor"),
                    ("PENDENTE_ORDENADOR", "Pendente Ordenador de Despesa"),
                    ("PENDENTE_CONSELHO", "Pendente Conselho Fiscal"),
                    ("PENDENTE_CONTADOR", "Pendente Revisão da Contadora"),
                    ("APROVADA", "Aprovada"),
                    ("REJEITADA", "Rejeitada"),
                ],
                default="PENDENTE_SUPERVISOR",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontingencia",
            name="data_revisao_contadora",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontingencia",
            name="exige_aprovacao_conselho",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcontingencia",
            name="exige_aprovacao_ordenador",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcontingencia",
            name="exige_revisao_contadora",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcontingencia",
            name="parecer_contadora",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontingencia",
            name="revisado_por_contadora",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontingencia",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE_SUPERVISOR", "Pendente Supervisor"),
                    ("PENDENTE_ORDENADOR", "Pendente Ordenador de Despesa"),
                    ("PENDENTE_CONSELHO", "Pendente Conselho Fiscal"),
                    ("PENDENTE_CONTADOR", "Pendente Revisão da Contadora"),
                    ("APROVADA", "Aprovada"),
                    ("REJEITADA", "Rejeitada"),
                ],
                default="PENDENTE_SUPERVISOR",
                max_length=30,
            ),
        ),
    ]
