"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (development) or the environment (production)
load_dotenv(BASE_DIR / '.env')

# Gemini AI API key – must be set via environment variable in production.
# Falls back to a non-functional dummy so the app starts locally without a key;
# any actual Gemini calls will return an authentication error until the key is set.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'AIzaSy-DUMMY-TEST-KEY-NOT-REAL')
CRECI_LETTERHEAD_PATH = os.getenv('CRECI_LETTERHEAD_PATH')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Must be set via the SECRET_KEY environment variable in production.
_secret_key = os.getenv('SECRET_KEY')
if not _secret_key:
    # Allow development without a .env file, but make the insecure fallback obvious.
    import warnings
    warnings.warn(
        "SECRET_KEY is not set via the environment. "
        "Using an insecure fallback – DO NOT use in production.",
        stacklevel=2,
    )
    _secret_key = 'django-insecure-fallback-key-for-local-dev-only-do-not-use-in-production'
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Comma-separated list of allowed hosts, e.g. "yourdomain.com,www.yourdomain.com"
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django_filters',
    'simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'commons.apps.CommonsConfig',
    'credores.apps.CredoresConfig',
    'pagamentos.apps.PagamentosConfig',
    'suprimentos.apps.SuprimentosConfig',
    'verbas_indenizatorias.apps.VerbasIndenizatoriasConfig',
        'fiscal.apps.FiscalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pagamentos.middleware.GlobalLoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'commons' / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': ['pagamentos.templatetags.fmt_builtin'],
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pagamentos.context_processors.alertas_contas_fixas',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'

# Redirect to home page after a successful login instead of the default /accounts/profile/
LOGIN_REDIRECT_URL = '/'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Use PostgreSQL in production (set DB_ENGINE env var) or fall back to SQLite for development.

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Set STATIC_ROOT via environment variable so no server-specific paths are
# committed to source control.  Falls back to a local 'staticfiles' directory
# which is safe for development and is already excluded in .gitignore.
STATIC_ROOT = os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

# ---------------------------------------------------------------------------
# PDF template settings
# ---------------------------------------------------------------------------
# Path to the CRECI-SC letterhead PDF used as a background for auto-generated
# documents (payment authorisations, fiscal-council opinions, etc.).
# Override via the CRECI_LETTERHEAD_PATH environment variable to use a
# different file per deployment without touching source code.
CRECI_LETTERHEAD_PATH = os.getenv(
    'CRECI_LETTERHEAD_PATH',
    str(BASE_DIR / 'processos' / 'pdf_templates' / 'papel_timbrado_creci_sc.pdf'),
)

# ---------------------------------------------------------------------------
# Reverse-proxy / Docker settings
# ---------------------------------------------------------------------------
# Comma-separated list of trusted origins for CSRF when running behind a
# reverse proxy such as Nginx.  Example: http://10.0.0.5,https://myapp.example.com
_csrf_trusted = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(',') if o.strip()]

# Trust the X-Forwarded-Proto header set by Nginx so Django knows the original
# request was HTTPS even though Gunicorn itself only sees HTTP.
# Only enabled when USE_X_FORWARDED_PROTO is set (i.e., when running behind a trusted proxy).
if os.getenv('USE_X_FORWARDED_PROTO', 'False').lower() in ('true', '1', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ---------------------------------------------------------------------------
# Production security settings
# These are only activated when DEBUG is False so they don't interfere with
# local development where HTTPS is typically not available.
# ---------------------------------------------------------------------------
if not DEBUG:
    # Allow disabling HTTPS redirect for local-network deployments that do not
    # use TLS yet (set SECURE_SSL_REDIRECT=False in the environment).
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    # Tell browsers to only connect via HTTPS for 1 year (including subdomains)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Prevent session and CSRF cookies from being sent over plain HTTP
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Prevent the site from being embedded in iframes (clickjacking protection)
    X_FRAME_OPTIONS = 'DENY'
    # Prevent browsers from guessing content types (MIME-sniffing protection)
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Test-run compatibility: avoid forced HTTPS redirects in Django test client
# requests so legacy tests can exercise view logic directly.
if "test" in sys.argv:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
