from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from processos.views import home_page, add_process_view, visualizar_pdf_processo, editar_processo, editar_processo_verbas, api_add_documento_verba, painel_impostos, contas_a_pagar, api_processar_boleto, api_extrair_codigos_barras_processo, api_extrair_codigos_barras_upload, add_pre_empenho_view, a_empenhar_view, avancar_para_pagamento_view, add_credor_view, edit_credor_view, credores_list_view, diarias_list_view, reembolsos_list_view, jetons_list_view, auxilios_list_view, add_diaria_view, add_reembolso_view, add_jeton_view, add_auxilio_view, verbas_panel_view, agrupar_verbas_view, agrupar_impostos_view, painel_comprovantes_view, api_fatiar_comprovantes, api_vincular_comprovantes, painel_conferencia_view, aprovar_conferencia_view, iniciar_conferencia_view, conferencia_processo_view, enviar_para_autorizacao, painel_autorizacao_view, autorizar_pagamento, aprovar_contabilizacao_view, aprovar_conselho_view, arquivar_processo_view, painel_conselho_view, painel_arquivamento_view, painel_contabilizacao_view, iniciar_contabilizacao_view, contabilizacao_processo_view, iniciar_conselho_view, conselho_processo_view, painel_suprimentos_view, gerenciar_suprimento_view, fechar_suprimento_view, add_suprimento_view, recusar_contabilizacao_view, recusar_autorizacao_view, recusar_conselho_view, api_extrair_nota, api_extracao_universal, api_dados_credor, api_tipos_documento_por_pagamento, painel_pendencias_view, alternar_ateste_nota, painel_liquidacoes_view, documentos_fiscais_view, api_toggle_documento_fiscal, api_salvar_nota_fiscal, api_detalhes_pagamento, separar_para_lancamento_bancario, lancamento_bancario, marcar_como_lancado, desmarcar_lancamento, api_processar_retencoes, gerar_dummy_pdf_view, api_valor_unitario_diaria, api_documentos_processo, auditoria_view, gerenciar_diaria_view, edit_reembolso_view, edit_jeton_view, edit_auxilio_view, add_contingencia_view, painel_contingencias_view, analisar_contingencia_view, api_processo_detalhes, painel_autorizacao_diarias_view, alternar_autorizacao_diaria, aprovar_diaria_view, gerar_autorizacao_pagamento_view, gerar_parecer_conselho_view, gerar_pcd_view, painel_reinf_view, gerar_lote_reinf_view, gerar_dados_fake_view, sincronizar_siscac, download_arquivo_seguro, registrar_devolucao_view, process_detail_view, painel_devolucoes_view, sincronizar_diarias, importar_diarias_view, download_template_diarias_csv, sincronizar_assinatura_view, reenviar_assinatura_view, minhas_solicitacoes_view, painel_contas_fixas_view, vincular_processo_fatura_view, add_conta_fixa_view, edit_conta_fixa_view, excluir_conta_fixa_view, painel_importacao_view, download_template_csv_credores, download_template_csv_contas, gerenciar_reunioes_view, montar_pauta_reuniao_view, analise_reuniao_view, iniciar_conselho_reuniao_view
from processos.ai_views import ai_extraction_page_view, api_testar_extracao
from processos.views import teste_pdf

urlpatterns = [
path('admin/', admin.site.urls),

# Rota raiz (Home)
path('', home_page, name='home_page'),
path('adicionar/', add_process_view, name='add_process'),
path('processo/<int:pk>/editar/', editar_processo, name='editar_processo'),
path('processo/<int:pk>/editar-verbas/', editar_processo_verbas, name='editar_processo_verbas'),
path('api/verba/<str:tipo_verba>/<int:pk>/add-documento/', api_add_documento_verba, name='api_add_documento_verba'),
path('processo/<int:processo_id>/pdf/', visualizar_pdf_processo, name='visualizar_pdf_processo'),
path('contas-a-pagar/', contas_a_pagar, name='contas_a_pagar'),
path('testador-ia/', ai_extraction_page_view, name='testador_ia'),
path('api/testar-extracao/', api_testar_extracao, name='api_testar_extracao'),

path('retencao-impostos/', painel_impostos, name='painel_impostos'),
path('api/processar-boleto/', api_processar_boleto, name='api_processar_boleto'),
path('api/processo/<int:pk>/extrair-codigos-barras/', api_extrair_codigos_barras_processo, name='api_extrair_codigos_barras_processo'),
path('api/extrair-codigos-barras-upload/', api_extrair_codigos_barras_upload, name='api_extrair_codigos_barras_upload'),
path('adicionar-pre-empenho/', add_pre_empenho_view, name='add_pre_empenho'),
path('a-empenhar/', a_empenhar_view, name='a_empenhar'),
path('processo/<int:pk>/avancar-para-pagamento/', avancar_para_pagamento_view, name='avancar_para_pagamento'),
path('adicionar-credor/', add_credor_view, name='add_credor'),
path('credores/', credores_list_view, name='credores_list'),
path('credores/<int:pk>/editar/', edit_credor_view, name='edit_credor'),
path('verbas/diarias/', diarias_list_view, name='diarias_list'),
path('verbas/reembolsos/', reembolsos_list_view, name='reembolsos_list'),
path('verbas/jetons/', jetons_list_view, name='jetons_list'),
path('verbas/auxilios/', auxilios_list_view, name='auxilios_list'),
path('verbas/diarias/nova/', add_diaria_view, name='add_diaria'),
path('verbas/diarias/<int:pk>/gerenciar/', gerenciar_diaria_view, name='gerenciar_diaria'),
path('verbas/reembolsos/novo/', add_reembolso_view, name='add_reembolso'),
path('verbas/jetons/novo/', add_jeton_view, name='add_jeton'),
path('verbas/auxilios/novo/', add_auxilio_view, name='add_auxilio'),
path('verbas/', verbas_panel_view, name='verbas_panel'),
path('verbas/reembolsos/<int:pk>/editar/', edit_reembolso_view, name='edit_reembolso'),
path('verbas/jetons/<int:pk>/editar/', edit_jeton_view, name='edit_jeton'),
path('verbas/auxilios/<int:pk>/editar/', edit_auxilio_view, name='edit_auxilio'),
path('verbas/agrupar/<str:tipo_verba>/', agrupar_verbas_view, name='agrupar_verbas'),
path('impostos/agrupar/', agrupar_impostos_view, name='agrupar_impostos'),
path('processos/comprovantes/', painel_comprovantes_view, name='painel_comprovantes'),
path('api/comprovantes/fatiar/', api_fatiar_comprovantes, name='api_fatiar_comprovantes'),
path('api/comprovantes/vincular/', api_vincular_comprovantes, name='api_vincular_comprovantes'),
path('processos/conferencia/', painel_conferencia_view, name='painel_conferencia'),
path('processos/conferencia/iniciar/', iniciar_conferencia_view, name='iniciar_conferencia'),
path('processos/conferencia/<int:pk>/revisar/', conferencia_processo_view, name='conferencia_processo'),
path('processos/conferencia/<int:pk>/aprovar/', aprovar_conferencia_view, name='aprovar_conferencia'),
path('processos/enviar-autorizacao/', enviar_para_autorizacao, name='enviar_para_autorizacao'),
path('processos/autorizacao/', painel_autorizacao_view, name='painel_autorizacao'),
path('processos/autorizar-pagamento/', autorizar_pagamento, name='autorizar_pagamento'),
# Contabilização
path('processos/contabilizacao/', painel_contabilizacao_view, name='painel_contabilizacao'),
path('processos/contabilizacao/iniciar/', iniciar_contabilizacao_view, name='iniciar_contabilizacao'),
path('processos/contabilizacao/<int:pk>/revisar/', contabilizacao_processo_view, name='contabilizacao_processo'),
path('processos/contabilizacao/<int:pk>/aprovar/', aprovar_contabilizacao_view, name='aprovar_contabilizacao'),

# Conselho Fiscal
path('processos/conselho/', painel_conselho_view, name='painel_conselho'),
path('processos/conselho/iniciar/', iniciar_conselho_view, name='iniciar_conselho'),
path('processos/conselho/<int:pk>/revisar/', conselho_processo_view, name='conselho_processo'),
path('processos/conselho/<int:pk>/aprovar/', aprovar_conselho_view, name='aprovar_conselho'),
# Reuniões do Conselho
path('processos/conselho/reunioes/', gerenciar_reunioes_view, name='gerenciar_reunioes'),
path('processos/conselho/reunioes/<int:reuniao_id>/montar-pauta/', montar_pauta_reuniao_view, name='montar_pauta_reuniao'),
path('processos/conselho/reunioes/<int:reuniao_id>/analisar/', analise_reuniao_view, name='analise_reuniao'),
path('processos/conselho/reunioes/<int:reuniao_id>/iniciar/', iniciar_conselho_reuniao_view, name='iniciar_conselho_reuniao'),

# Arquivamento
path('processos/arquivamento/', painel_arquivamento_view, name='painel_arquivamento'),
path('processos/arquivamento/<int:pk>/aprovar/', arquivar_processo_view, name='arquivar_processo'),
path('suprimentos/', painel_suprimentos_view, name='painel_suprimentos'),
path('suprimentos/<int:pk>/gerenciar/', gerenciar_suprimento_view, name='gerenciar_suprimento'),
path('suprimentos/<int:pk>/fechar/', fechar_suprimento_view, name='fechar_suprimento'),
path('suprimentos/novo/', add_suprimento_view, name='add_suprimento'),
path('processos/contabilizacao/<int:pk>/recusar/', recusar_contabilizacao_view, name='recusar_contabilizacao'),
path('processos/autorizacao/<int:pk>/recusar/', recusar_autorizacao_view, name='recusar_autorizacao'),
path('processos/conselho/<int:pk>/recusar/', recusar_conselho_view, name='recusar_conselho'),
path('api/extrair-nota/', api_extrair_nota, name='api_extrair_nota'),
path('api/extracao-universal/', api_extracao_universal, name='api_extracao_universal'),
path('api/credor/<int:credor_id>/', api_dados_credor, name='api_dados_credor'),
path('api/valor-unitario-diaria/<int:beneficiario_id>/', api_valor_unitario_diaria, name='api_valor_unitario_diaria'),
path('api/documentos-por-pagamento/', api_tipos_documento_por_pagamento, name='api_documentos_pagamento'),
path('pendencias/', painel_pendencias_view, name='painel_pendencias'),
path('liquidacoes/', painel_liquidacoes_view, name='painel_liquidacoes'),
path('liquidacoes/atestar/<int:pk>/', alternar_ateste_nota, name='alternar_ateste_nota'),
path('verbas/diarias/autorizacao/', painel_autorizacao_diarias_view, name='painel_autorizacao_diarias'),
path('verbas/diarias/autorizacao/<int:pk>/alternar/', alternar_autorizacao_diaria, name='alternar_autorizacao_diaria'),
path('verbas/diarias/<int:diaria_id>/aprovar/', aprovar_diaria_view, name='aprovar_diaria'),
path('processo/<int:pk>/documentos-fiscais/', documentos_fiscais_view, name='documentos_fiscais'),
path('api/processo/<int:processo_pk>/toggle-documento-fiscal/<int:documento_pk>/', api_toggle_documento_fiscal, name='api_toggle_documento_fiscal'),
path('api/processo/<int:processo_pk>/salvar-nota-fiscal/<int:nota_pk>/', api_salvar_nota_fiscal, name='api_salvar_nota_fiscal'),
path('processo/<int:pk>/gerar-dummy-pdf/', gerar_dummy_pdf_view, name='gerar_dummy_pdf'),
path('api/detalhes-pagamento/', api_detalhes_pagamento, name='api_detalhes_pagamento'),
path('processos/separar-lancamento/', separar_para_lancamento_bancario, name='separar_para_lancamento_bancario'),
path('processos/lancamento-bancario/', lancamento_bancario, name='lancamento_bancario'),
path('processos/marcar-lancado/', marcar_como_lancado, name='marcar_como_lancado'),
path('api/processar-retencoes/', api_processar_retencoes, name='api_processar_retencoes'),
path('processos/desmarcar-lancamento/', desmarcar_lancamento, name='desmarcar_lancamento'),
path('api/processo/<int:processo_id>/documentos/', api_documentos_processo, name='api_documentos_processo'),
path('auditoria/', auditoria_view, name='auditoria'),
path('contingencias/', painel_contingencias_view, name='painel_contingencias'),
path('contingencias/nova/', add_contingencia_view, name='add_contingencia'),
path('contingencias/<int:pk>/analisar/', analisar_contingencia_view, name='analisar_contingencia'),
path('api/processo_detalhes/', api_processo_detalhes, name='api_processo_detalhes'),
# Documentos PDF oficiais
path('processo/<int:pk>/autorizacao-pagamento/', gerar_autorizacao_pagamento_view, name='gerar_autorizacao_pagamento'),
path('processo/<int:pk>/parecer-conselho/', gerar_parecer_conselho_view, name='gerar_parecer_conselho'),
path('verbas/diarias/<int:pk>/pcd/', gerar_pcd_view, name='gerar_pcd'),
path('reinf/painel/', painel_reinf_view, name='painel_reinf'),
path('reinf/gerar-lotes/', gerar_lote_reinf_view, name='gerar_lote_reinf'),
path('dados-fake/', gerar_dados_fake_view, name='gerar_dados_fake'),
path('importar-siscac/', painel_importacao_view, name='painel_importacao'),
path('importar-siscac/template-credores/', download_template_csv_credores, name='template_csv_credores'),
path('importar-siscac/template-contas/', download_template_csv_contas, name='template_csv_contas'),
path('testes/pdfs/', teste_pdf.painel_teste_pdfs, name='painel_teste_pdfs'),
path('testes/pdfs/gerar/<str:doc_type>/', teste_pdf.gerar_pdf_fake_view, name='gerar_pdf_fake'),
path('fluxo/sincronizar-siscac/', sincronizar_siscac, name='sincronizar_siscac'),
path('documentos/secure/<str:tipo_documento>/<int:documento_id>/', download_arquivo_seguro, name='download_arquivo_seguro'),
path('processo/<int:pk>/', process_detail_view, name='process_detail'),
path('processo/<int:processo_id>/devolucao/', registrar_devolucao_view, name='registrar_devolucao'),
path('devolucoes/', painel_devolucoes_view, name='painel_devolucoes'),
path('verbas/sincronizar-diarias/', sincronizar_diarias, name='sincronizar_diarias'),
path('verbas/diarias/importar/', importar_diarias_view, name='importar_diarias'),
path('verbas/diarias/template-csv/', download_template_diarias_csv, name='download_template_diarias_csv'),
path('verbas/diarias/<int:assinatura_id>/sincronizar/', sincronizar_assinatura_view, name='sincronizar_assinatura'),
path('verbas/diarias/<int:diaria_id>/reenviar-assinatura/', reenviar_assinatura_view, name='reenviar_assinatura'),
path('verbas/minhas-solicitacoes/', minhas_solicitacoes_view, name='minhas_solicitacoes'),
path('contas-fixas/', painel_contas_fixas_view, name='painel_contas_fixas'),
path('contas-fixas/nova/', add_conta_fixa_view, name='add_conta_fixa'),
path('contas-fixas/<int:pk>/editar/', edit_conta_fixa_view, name='edit_conta_fixa'),
path('contas-fixas/<int:pk>/excluir/', excluir_conta_fixa_view, name='excluir_conta_fixa'),
path('contas-fixas/<int:fatura_id>/vincular/', vincular_processo_fatura_view, name='vincular_processo_fatura'),
path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
