# Generated by Django 6.0.3 on 2026-04-09 16:39

import credores.models
import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContasBancarias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Conta"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCargosFuncoes",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Grupo Relacionado",
                    ),
                ),
                ("cargo_funcao", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Cargo / Função",
                "verbose_name_plural": "historical Cargos e Funções",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContaFixa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        help_text="Ex: Conta de Luz - Sede",
                        max_length=200,
                        verbose_name="Referência / Descrição",
                    ),
                ),
                (
                    "dia_vencimento",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia Padrão de Vencimento",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Conta Ativa"),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Mês a partir do qual as faturas mensais serão geradas.",
                        verbose_name="Data de Início",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Conta Fixa",
                "verbose_name_plural": "historical Contas Fixas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContasBancarias",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Conta"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contas bancarias",
                "verbose_name_plural": "historical contas bancariass",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCredor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=50,
                        validators=[credores.models.validar_cpf_cnpj],
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Chave PIX do credor",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone do credor",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email do credor",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PF", "Pessoa Física (CPF)"),
                            ("PJ", "Pessoa Jurídica (CNPJ)"),
                            ("EX", "Exterior / Outros"),
                        ],
                        default="PJ",
                        max_length=2,
                        verbose_name="Tipo de Pessoa",
                    ),
                ),
                (
                    "codigo_servico_padrao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 100000001 (Limpeza). Será herdado automaticamente pelas Notas Fiscais deste credor.",
                        max_length=9,
                        null=True,
                        verbose_name="Cód. Serviço Padrão INSS (Tabela 06)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Credor Ativo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical credor",
                "verbose_name_plural": "historical credors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFaturaMensal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fatura Mensal",
                "verbose_name_plural": "historical Faturas Mensais",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CargosFuncoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Grupo Relacionado",
                    ),
                ),
                ("cargo_funcao", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cargo / Função",
                "verbose_name_plural": "Cargos e Funções",
                "unique_together": {("grupo", "cargo_funcao")},
            },
        ),
        migrations.CreateModel(
            name="Credor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=50,
                        validators=[credores.models.validar_cpf_cnpj],
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Chave PIX do credor",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefone do credor",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email do credor",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PF", "Pessoa Física (CPF)"),
                            ("PJ", "Pessoa Jurídica (CNPJ)"),
                            ("EX", "Exterior / Outros"),
                        ],
                        default="PJ",
                        max_length=2,
                        verbose_name="Tipo de Pessoa",
                    ),
                ),
                (
                    "codigo_servico_padrao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 100000001 (Limpeza). Será herdado automaticamente pelas Notas Fiscais deste credor.",
                        max_length=9,
                        null=True,
                        verbose_name="Cód. Serviço Padrão INSS (Tabela 06)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Credor Ativo")),
                (
                    "cargo_funcao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.cargosfuncoes",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.contasbancarias",
                        verbose_name="Conta Credor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contasbancarias",
            name="titular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contas_bancarias",
                to="credores.credor",
            ),
        ),
        migrations.CreateModel(
            name="ContaFixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        help_text="Ex: Conta de Luz - Sede",
                        max_length=200,
                        verbose_name="Referência / Descrição",
                    ),
                ),
                (
                    "dia_vencimento",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia Padrão de Vencimento",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Conta Ativa"),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Mês a partir do qual as faturas mensais serão geradas.",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "credor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.credor",
                        verbose_name="Credor/Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Fixa",
                "verbose_name_plural": "Contas Fixas",
            },
        ),
        migrations.CreateModel(
            name="FaturaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                (
                    "conta_fixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faturas",
                        to="credores.contafixa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Mensal",
                "verbose_name_plural": "Faturas Mensais",
            },
        ),
    ]
