# Generated by Django 6.0.3 on 2026-04-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credores", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="credor",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credor_vinculado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Portal",
            ),
        ),
        migrations.AddField(
            model_name="historicalcredor",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Portal",
            ),
        ),
    ]
