# Generated by Django 6.0.3 on 2026-04-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credores", "0002_faturamensal_processo_vinculado"),
    ]

    operations = [
        migrations.AddField(
            model_name="credor",
            name="is_entidade_imune",
            field=models.BooleanField(
                default=False,
                help_text="Marque se a entidade é legalmente imune/isenta de tributação (ex: entidades públicas, igrejas, ONGs).",
                verbose_name="Entidade Imune/Isenta (EFD-Reinf)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcredor",
            name="is_entidade_imune",
            field=models.BooleanField(
                default=False,
                help_text="Marque se a entidade é legalmente imune/isenta de tributação (ex: entidades públicas, igrejas, ONGs).",
                verbose_name="Entidade Imune/Isenta (EFD-Reinf)",
            ),
        ),
    ]
