# Generated by Django 6.0.3 on 2026-04-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagamentos",
            "0002_formaspagamento_opcoesetiqueta_statusopcoespendencia_and_more",
        ),
        ("suprimentos", "0002_alter_documentosuprimentodefundos_tipo_and_more"),
        (
            "verbas_indenizatorias",
            "0002_alter_diaria_objetivo_alter_documentoauxilio_tipo_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="TiposDeDocumento",
        ),
        migrations.DeleteModel(
            name="TiposDePagamento",
        ),
    ]
