# Generated by Django 6.0.3 on 2026-05-14

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_delete_contas_fixas_models"),
        ("pagamentos", "0005_alter_processo_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaFixa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("referencia", models.CharField(help_text="Ex: Conta de Luz - Sede", max_length=200, verbose_name="Referência / Descrição")),
                ("dia_vencimento", models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name="Dia Padrão de Vencimento")),
                ("ativa", models.BooleanField(default=True, verbose_name="Conta Ativa")),
                ("data_inicio", models.DateField(default=datetime.date.today, help_text="Mês a partir do qual as faturas mensais serão geradas.", verbose_name="Data de Início")),
                ("credor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="cadastros.credor", verbose_name="Credor/Fornecedor")),
            ],
            options={
                "verbose_name": "Conta Fixa",
                "verbose_name_plural": "Contas Fixas",
            },
        ),
        migrations.CreateModel(
            name="HistoricalContaFixa",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("referencia", models.CharField(help_text="Ex: Conta de Luz - Sede", max_length=200, verbose_name="Referência / Descrição")),
                ("dia_vencimento", models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name="Dia Padrão de Vencimento")),
                ("ativa", models.BooleanField(default=True, verbose_name="Conta Ativa")),
                ("data_inicio", models.DateField(default=datetime.date.today, help_text="Mês a partir do qual as faturas mensais serão geradas.", verbose_name="Data de Início")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("credor", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="cadastros.credor", verbose_name="Credor/Fornecedor")),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "historical Conta Fixa",
                "verbose_name_plural": "historical Contas Fixas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFaturaMensal",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("conta_fixa", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="pagamentos.contafixa")),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("processo_vinculado", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="pagamentos.processo")),
            ],
            options={
                "verbose_name": "historical Fatura Mensal",
                "verbose_name_plural": "historical Faturas Mensais",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FaturaMensal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                ("conta_fixa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="faturas", to="pagamentos.contafixa")),
                ("processo_vinculado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="faturas_vinculadas", to="pagamentos.processo")),
            ],
            options={
                "verbose_name": "Fatura Mensal",
                "verbose_name_plural": "Faturas Mensais",
                "unique_together": {("conta_fixa", "mes_referencia")},
            },
        ),
    ]
