# Generated by Django 6.0.3 on 2026-05-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0006_add_contas_fixas_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processo",
            options={
                "permissions": [
                    ("operador_contas_a_pagar", "Pode operar contas a pagar"),
                    (
                        "pode_visualizar_processos_pagamento",
                        "Pode visualizar processos de pagamento",
                    ),
                    (
                        "pode_editar_processos_pagamento",
                        "Pode editar processos de pagamento",
                    ),
                    (
                        "pode_aprovar_contingencia_supervisor",
                        "Pode aprovar contingências na etapa de supervisão/gerência",
                    ),
                    (
                        "pode_aprovar_contingencia_ordenador",
                        "Pode aprovar contingências na etapa do Ordenador de Despesa",
                    ),
                    (
                        "pode_aprovar_contingencia_conselho",
                        "Pode aprovar contingências na etapa do Conselho Fiscal",
                    ),
                    (
                        "pode_revisar_contingencia_contadora",
                        "Pode realizar a revisão contábil final de contingências",
                    ),
                    (
                        "pode_atestar_liquidacao",
                        "Pode atestar notas fiscais (Fiscal do Contrato)",
                    ),
                    (
                        "pode_autorizar_pagamento",
                        "Pode autorizar pagamentos (Ordenador)",
                    ),
                    ("pode_contabilizar", "Pode registrar a contabilização (Contador)"),
                    ("pode_auditar_conselho", "Pode aprovar no Conselho Fiscal"),
                    (
                        "pode_arquivar",
                        "Pode realizar o arquivamento definitivo de processos",
                    ),
                ]
            },
        ),
    ]
