# Generated by Django 6.0.3 on 2026-04-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagamentos",
            "0002_formaspagamento_opcoesetiqueta_statusopcoespendencia_and_more",
        ),
        ("verbas_indenizatorias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaria",
            name="objetivo",
            field=models.TextField(verbose_name="Objetivo da Viagem"),
        ),
        migrations.AlterField(
            model_name="documentoauxilio",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="documentocomprovacao",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="documentodiaria",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="documentojeton",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="documentoreembolso",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiaria",
            name="objetivo",
            field=models.TextField(verbose_name="Objetivo da Viagem"),
        ),
        migrations.AlterField(
            model_name="historicaldocumentoauxilio",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentocomprovacao",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentodiaria",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentojeton",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.tiposdocumento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentoreembolso",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.tiposdocumento",
            ),
        ),
    ]
