# Generated by Django 6.0.3 on 2026-04-09 16:39

import django.core.validators
import fiscal.models
import fluxo.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodigosImposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "regra_competencia",
                    models.CharField(
                        choices=[
                            ("emissao", "Pela Data de Emissão da NF"),
                            ("pagamento", "Pela Data de Pagamento"),
                        ],
                        default="emissao",
                        max_length=15,
                    ),
                ),
                (
                    "aliquota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "natureza_rendimento",
                    models.CharField(
                        blank=True,
                        help_text="Código de 5 dígitos (Tabela 01 do SPED). Ex: 15001, 17001. Mapeia o código de receita para o XML.",
                        max_length=5,
                        null=True,
                        verbose_name="Natureza do Rendimento (EFD-Reinf)",
                    ),
                ),
                (
                    "serie_reinf",
                    models.CharField(
                        choices=[
                            ("NONE", "Não mapeado"),
                            ("S2000", "Série 2000 – Previdenciário (INSS)"),
                            ("S4000", "Série 4000 – Retenções Federais (IRRF/CSRF)"),
                        ],
                        default="NONE",
                        help_text="Classifica o imposto para geração do XML EFD-Reinf: S2000 = INSS, S4000 = IR/CSLL/PIS/COFINS.",
                        max_length=6,
                        verbose_name="Série EFD-Reinf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj_emitente",
                    models.CharField(
                        max_length=20, validators=[fiscal.models.validar_cpf_cnpj]
                    ),
                ),
                ("numero_nota_fiscal", models.CharField(max_length=50)),
                ("data_emissao", models.DateField()),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("atestada", models.BooleanField(default=False)),
                (
                    "serie_nota_fiscal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Série"
                    ),
                ),
                (
                    "codigo_servico_inss",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Cód. Serviço INSS (Tabela 06 Reinf)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalComprovanteDePagamento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_comprovante",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número do Comprovante",
                    ),
                ),
                (
                    "credor_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Credor (Texto)",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                        verbose_name="Arquivo do Comprovante",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Comprovante de Pagamento",
                "verbose_name_plural": "historical Comprovantes de Pagamento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cnpj_emitente",
                    models.CharField(
                        max_length=20, validators=[fiscal.models.validar_cpf_cnpj]
                    ),
                ),
                ("numero_nota_fiscal", models.CharField(max_length=50)),
                ("data_emissao", models.DateField()),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("atestada", models.BooleanField(default=False)),
                (
                    "serie_nota_fiscal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Série"
                    ),
                ),
                (
                    "codigo_servico_inss",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Cód. Serviço INSS (Tabela 06 Reinf)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento fiscal",
                "verbose_name_plural": "historical documento fiscals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRetencaoImposto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "rendimento_tributavel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base de Cálculo / Rend. Tributável",
                    ),
                ),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Retido",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        blank=True,
                        help_text="Salvo internamente como YYYY-MM-01, exibido como MM/AAAA",
                        null=True,
                        verbose_name="Mês de Competência",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical retencao imposto",
                "verbose_name_plural": "historical retencao impostos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RetencaoImposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rendimento_tributavel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base de Cálculo / Rend. Tributável",
                    ),
                ),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Retido",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        blank=True,
                        help_text="Salvo internamente como YYYY-MM-01, exibido como MM/AAAA",
                        null=True,
                        verbose_name="Mês de Competência",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusChoicesRetencoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
