# Generated by Django 6.0.3 on 2026-04-09 16:39

import commons.shared.file_validators
import django.core.validators
import django.db.models.deletion
import fiscal.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "__first__"),
        ("credores", "0001_initial"),
        ("pagamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigosImposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "regra_competencia",
                    models.CharField(
                        choices=[
                            ("emissao", "Pela Data de Emissão da NF"),
                            ("pagamento", "Pela Data de Pagamento"),
                        ],
                        default="emissao",
                        max_length=15,
                    ),
                ),
                (
                    "aliquota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "natureza_rendimento",
                    models.CharField(
                        blank=True,
                        help_text="Código de 5 dígitos (Tabela 01 do SPED). Ex: 15001, 17001. Mapeia o código de receita para o XML.",
                        max_length=5,
                        null=True,
                        verbose_name="Natureza do Rendimento (EFD-Reinf)",
                    ),
                ),
                (
                    "serie_reinf",
                    models.CharField(
                        choices=[
                            ("NONE", "Não mapeado"),
                            ("S2000", "Série 2000 – Previdenciário (INSS)"),
                            ("S4000", "Série 4000 – Retenções Federais (IRRF/CSRF)"),
                        ],
                        default="NONE",
                        help_text="Classifica o imposto para geração do XML EFD-Reinf: S2000 = INSS, S4000 = IR/CSLL/PIS/COFINS.",
                        max_length=6,
                        verbose_name="Série EFD-Reinf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DadosContribuinte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14, validators=[fiscal.models.validar_cpf_cnpj]
                    ),
                ),
                ("razao_social", models.CharField(max_length=255)),
                ("tipo_inscricao", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Dados do Contribuinte",
                "verbose_name_plural": "Dados do Contribuinte",
                "db_table": "credores_dadoscontribuinte",
            },
        ),
        migrations.CreateModel(
            name="DocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj_emitente",
                    models.CharField(
                        max_length=20, validators=[fiscal.models.validar_cpf_cnpj]
                    ),
                ),
                ("numero_nota_fiscal", models.CharField(max_length=50)),
                ("data_emissao", models.DateField()),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("atestada", models.BooleanField(default=False)),
                (
                    "serie_nota_fiscal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Série"
                    ),
                ),
                (
                    "codigo_servico_inss",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Cód. Serviço INSS (Tabela 06 Reinf)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDadosContribuinte",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14, validators=[fiscal.models.validar_cpf_cnpj]
                    ),
                ),
                ("razao_social", models.CharField(max_length=255)),
                ("tipo_inscricao", models.IntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Dados do Contribuinte",
                "verbose_name_plural": "historical Dados do Contribuinte",
                "db_table": "credores_historicaldadoscontribuinte",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cnpj_emitente",
                    models.CharField(
                        max_length=20, validators=[fiscal.models.validar_cpf_cnpj]
                    ),
                ),
                ("numero_nota_fiscal", models.CharField(max_length=50)),
                ("data_emissao", models.DateField()),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("atestada", models.BooleanField(default=False)),
                (
                    "serie_nota_fiscal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Série"
                    ),
                ),
                (
                    "codigo_servico_inss",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        verbose_name="Cód. Serviço INSS (Tabela 06 Reinf)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento fiscal",
                "verbose_name_plural": "historical documento fiscals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRetencaoImposto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "rendimento_tributavel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base de Cálculo / Rend. Tributável",
                    ),
                ),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Retido",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        blank=True,
                        help_text="Salvo internamente como YYYY-MM-01, exibido como MM/AAAA",
                        null=True,
                        verbose_name="Mês de Competência",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical retencao imposto",
                "verbose_name_plural": "historical retencao impostos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RetencaoImposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rendimento_tributavel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base de Cálculo / Rend. Tributável",
                    ),
                ),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Retido",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        blank=True,
                        help_text="Salvo internamente como YYYY-MM-01, exibido como MM/AAAA",
                        null=True,
                        verbose_name="Mês de Competência",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusChoicesRetencoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LiquidacaoDocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documento_fiscal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacao",
                        to="fiscal.documentofiscal",
                        verbose_name="Documento Fiscal",
                    ),
                ),
                (
                    "fiscal_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquidacoes_fiscalizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fiscal do Contrato",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="ID do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="nome_emitente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="credores.credor",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_fiscais",
                to="pagamentos.processo",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Tipo do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="ID do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldadoscontribuinte",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="nome_emitente",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="credores.credor",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="processo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.processo",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="beneficiario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="credores.credor",
                verbose_name="Beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="codigo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fiscal.codigosimposto",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="nota_fiscal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fiscal.documentofiscal",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="processo_pagamento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="O Processo agrupado gerado para pagar esta retenção ao órgão arrecadador.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pagamentos.processo",
                verbose_name="Processo de Recolhimento",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="beneficiario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retencoes",
                to="credores.credor",
                verbose_name="Beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="codigo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fiscal.codigosimposto"
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="nota_fiscal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retencoes",
                to="fiscal.documentofiscal",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="processo_pagamento",
            field=models.ForeignKey(
                blank=True,
                help_text="O Processo agrupado gerado para pagar esta retenção ao órgão arrecadador.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impostos_recolhidos",
                to="pagamentos.processo",
                verbose_name="Processo de Recolhimento",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fiscal.statuschoicesretencoes",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fiscal.statuschoicesretencoes",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentofiscal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serie_nota_fiscal__isnull", False)),
                fields=("processo", "numero_nota_fiscal", "serie_nota_fiscal"),
                name="unique_nf_por_processo",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoPagamentoImposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        help_text="Normalizado internamente para o primeiro dia do mês (YYYY-MM-01).",
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "relatorio_retencoes",
                    models.FileField(
                        upload_to=fiscal.models._upload_documento_pagamento_imposto,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                        verbose_name="Relatório de Retenções",
                    ),
                ),
                (
                    "guia_recolhimento",
                    models.FileField(
                        upload_to=fiscal.models._upload_documento_pagamento_imposto,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                        verbose_name="Guia de Recolhimento",
                    ),
                ),
                (
                    "comprovante_pagamento",
                    models.FileField(
                        upload_to=fiscal.models._upload_documento_pagamento_imposto,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                        verbose_name="Comprovante de Pagamento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_imposto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fiscal.codigosimposto",
                        verbose_name="Código de Imposto",
                    ),
                ),
                (
                    "retencao",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_pagamento",
                        to="fiscal.retencaoimposto",
                        verbose_name="Retenção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Pagamento de Imposto",
                "verbose_name_plural": "Documentos de Pagamento de Imposto",
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoPagamentoImposto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        help_text="Normalizado internamente para o primeiro dia do mês (YYYY-MM-01).",
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "relatorio_retencoes",
                    models.TextField(max_length=100, verbose_name="Relatório de Retenções"),
                ),
                (
                    "guia_recolhimento",
                    models.TextField(max_length=100, verbose_name="Guia de Recolhimento"),
                ),
                (
                    "comprovante_pagamento",
                    models.TextField(max_length=100, verbose_name="Comprovante de Pagamento"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "codigo_imposto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fiscal.codigosimposto",
                        verbose_name="Código de Imposto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retencao",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fiscal.retencaoimposto",
                        verbose_name="Retenção",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento pagamento imposto",
                "verbose_name_plural": "historical documento pagamento impostos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="documentopagamentoimposto",
            constraint=models.UniqueConstraint(
                fields=("retencao", "codigo_imposto", "competencia"),
                name="unique_doc_pagamento_por_retencao_codigo_competencia",
            ),
        ),
    ]
