# Generated by Django 6.0.3 on 2026-04-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.contrib.contenttypes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "__first__"),
        ("credores", "0002_initial"),
        ("fiscal", "0001_initial"),
        ("fluxo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentofiscal",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="ID do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="fiscal_contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_fiscalizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fiscal do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="nome_emitente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="credores.credor",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_fiscais",
                to="fluxo.processo",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Tipo do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="ID do Documento Vinculado",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="fiscal_contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fiscal do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldadoscontribuinte",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="nome_emitente",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="credores.credor",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="processo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fluxo.processo",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="beneficiario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="credores.credor",
                verbose_name="Beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="codigo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fiscal.codigosimposto",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="nota_fiscal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fiscal.documentofiscal",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="processo_pagamento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="O Processo agrupado gerado para pagar esta retenção ao órgão arrecadador.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fluxo.processo",
                verbose_name="Processo de Recolhimento",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="beneficiario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retencoes",
                to="credores.credor",
                verbose_name="Beneficiário",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="codigo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="fiscal.codigosimposto"
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="nota_fiscal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retencoes",
                to="fiscal.documentofiscal",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="processo_pagamento",
            field=models.ForeignKey(
                blank=True,
                help_text="O Processo agrupado gerado para pagar esta retenção ao órgão arrecadador.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impostos_recolhidos",
                to="fluxo.processo",
                verbose_name="Processo de Recolhimento",
            ),
        ),
        migrations.AddField(
            model_name="retencaoimposto",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fiscal.statuschoicesretencoes",
            ),
        ),
        migrations.AddField(
            model_name="historicalretencaoimposto",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="fiscal.statuschoicesretencoes",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentofiscal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serie_nota_fiscal__isnull", False)),
                fields=("processo", "numero_nota_fiscal", "serie_nota_fiscal"),
                name="unique_nf_por_processo",
            ),
        ),
    ]
