# Generated by Django 6.0.3 on 2026-04-20 01:26

import commons.shared.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldocumentopagamentoimposto",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Documento de Pagamento de Imposto",
                "verbose_name_plural": "historical Documentos de Pagamento de Imposto",
            },
        ),
        migrations.AlterField(
            model_name="historicaldocumentopagamentoimposto",
            name="comprovante_pagamento",
            field=models.TextField(
                max_length=100,
                validators=[commons.shared.file_validators.validar_arquivo_seguro],
                verbose_name="Comprovante de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentopagamentoimposto",
            name="guia_recolhimento",
            field=models.TextField(
                max_length=100,
                validators=[commons.shared.file_validators.validar_arquivo_seguro],
                verbose_name="Guia de Recolhimento",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocumentopagamentoimposto",
            name="relatorio_retencoes",
            field=models.TextField(
                max_length=100,
                validators=[commons.shared.file_validators.validar_arquivo_seguro],
                verbose_name="Relatório de Retenções",
            ),
        ),
    ]
