# Generated by Django 6.0.3 on 2026-04-19

import commons.shared.file_validators
import django.db.models.deletion
import fiscal.models
from django.conf import settings
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fiscal", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoPagamentoImposto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        help_text="Normalizado internamente para o primeiro dia do mês (YYYY-MM-01).",
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "relatorio_retencoes",
                    models.FileField(
                        upload_to=fiscal.models._upload_documento_pagamento_imposto,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                        verbose_name="Relatório de Retenções",
                    ),
                ),
                (
                    "guia_recolhimento",
                    models.FileField(
                        upload_to=fiscal.models._upload_documento_pagamento_imposto,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                        verbose_name="Guia de Recolhimento",
                    ),
                ),
                (
                    "comprovante_pagamento",
                    models.FileField(
                        upload_to=fiscal.models._upload_documento_pagamento_imposto,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                        verbose_name="Comprovante de Pagamento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_imposto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fiscal.codigosimposto",
                        verbose_name="Código de Imposto",
                    ),
                ),
                (
                    "retencao",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_pagamento",
                        to="fiscal.retencaoimposto",
                        verbose_name="Retenção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Pagamento de Imposto",
                "verbose_name_plural": "Documentos de Pagamento de Imposto",
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoPagamentoImposto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(
                        help_text="Normalizado internamente para o primeiro dia do mês (YYYY-MM-01).",
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "relatorio_retencoes",
                    models.TextField(max_length=100, verbose_name="Relatório de Retenções"),
                ),
                (
                    "guia_recolhimento",
                    models.TextField(max_length=100, verbose_name="Guia de Recolhimento"),
                ),
                (
                    "comprovante_pagamento",
                    models.TextField(max_length=100, verbose_name="Comprovante de Pagamento"),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "codigo_imposto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fiscal.codigosimposto",
                        verbose_name="Código de Imposto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retencao",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fiscal.retencaoimposto",
                        verbose_name="Retenção",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento pagamento imposto",
                "verbose_name_plural": "historical documento pagamento impostos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="documentopagamentoimposto",
            constraint=models.UniqueConstraint(
                fields=("retencao", "codigo_imposto", "competencia"),
                name="unique_doc_pagamento_por_retencao_codigo_competencia",
            ),
        ),
    ]
