# Generated by Django 6.0.3 on 2026-04-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_alter_historicaldocumentopagamentoimposto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="descIsencao",
            field=models.CharField(
                blank=True,
                help_text="Fundamentação legal ou descrição resumida da isenção/imunidade.",
                max_length=255,
                null=True,
                verbose_name="Descrição da Isenção",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="is_rendimento_isento",
            field=models.BooleanField(
                default=False,
                help_text="Marque se o pagamento é para entidade imune ou isenta de tributação (sem retenção).",
                verbose_name="Rendimento Isento/Imune",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocumentofiscal",
            name="tpIsencao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Imunidade"),
                    ("02", "Pessoa Jurídica isenta"),
                    ("03", "Rendimento isento"),
                    ("99", "Outras isençõe/imunidades"),
                ],
                help_text="Código do tipo de isenção conforme Tabela do SPED. Ex: '99' para outras isençõe/imunidades.",
                max_length=2,
                null=True,
                verbose_name="Tipo de Isenção (Reinf)",
            ),
        ),
    ]
