# Generated by Django 6.0.3 on 2026-04-09 16:39

import django.core.validators
import django.db.models.deletion
import fluxo.models
import fluxo.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credores", "0001_initial"),
        ("fluxo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeiosDeTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meio_de_transporte", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatusChoicesVerbasIndenizatorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_choice", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TiposDeVerbasIndenizatorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_verba_indenizatoria",
                    models.CharField(max_length=100, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuxilioRepresentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sequencial",
                    models.CharField(max_length=50, verbose_name="Número Sequencial"),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        help_text="Preencha se for representação em evento específico",
                        max_length=200,
                        null=True,
                        verbose_name="Evento/Motivo da Representação",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "PF"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.credor",
                        verbose_name="Beneficiário",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auxilios_representacao",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_solicitacao",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Concessão Inicial"),
                            ("PRORROGACAO", "Prorrogação"),
                            ("COMPLEMENTACAO", "Complementação"),
                        ],
                        default="INICIAL",
                        max_length=20,
                    ),
                ),
                ("data_saida", models.DateField(verbose_name="Data de Saída")),
                ("data_retorno", models.DateField(verbose_name="Data de Retorno")),
                (
                    "cidade_origem",
                    models.CharField(max_length=50, verbose_name="Cidade de Origem"),
                ),
                (
                    "cidade_destino",
                    models.CharField(
                        max_length=100, verbose_name="Cidade(s) de Destino"
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(max_length=200, verbose_name="Objetivo da Viagem"),
                ),
                (
                    "quantidade_diarias",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Quantidade de Diárias",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "autorizada",
                    models.BooleanField(default=False, verbose_name="Autorizada"),
                ),
                (
                    "numero_siscac",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Nº SISCAC",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "PF"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_como_beneficiario",
                        to="credores.credor",
                        verbose_name="Beneficiário",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diarias",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "proponente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diarias_propostas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proponente",
                    ),
                ),
                (
                    "meio_de_transporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="verbas_indenizatorias.meiosdetransporte",
                        verbose_name="Meio de Transporte",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoAuxilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=fluxo.models.caminho_documento,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "auxilio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="verbas_indenizatorias.auxiliorepresentacao",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fluxo.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentoDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=fluxo.models.caminho_documento,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fluxo.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoAuxilio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "auxilio",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.auxiliorepresentacao",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento auxilio",
                "verbose_name_plural": "historical documento auxilios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoDiaria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento diaria",
                "verbose_name_plural": "historical documento diarias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Jeton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sequencial",
                    models.CharField(max_length=50, verbose_name="Número Sequencial"),
                ),
                (
                    "reuniao",
                    models.CharField(
                        max_length=7, verbose_name="Reunião/Sessão de Referência"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "PF"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.credor",
                        verbose_name="Conselheiro(a)",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jetons",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoJeton",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.tiposdedocumento",
                    ),
                ),
                (
                    "jeton",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.jeton",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento jeton",
                "verbose_name_plural": "historical documento jetons",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentoJeton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=fluxo.models.caminho_documento,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fluxo.tiposdedocumento",
                    ),
                ),
                (
                    "jeton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="verbas_indenizatorias.jeton",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReembolsoCombustivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sequencial",
                    models.CharField(max_length=50, verbose_name="Número Sequencial"),
                ),
                ("data_saida", models.DateField(verbose_name="Data de Saída")),
                ("data_retorno", models.DateField(verbose_name="Data de Retorno")),
                (
                    "cidade_origem",
                    models.CharField(max_length=50, verbose_name="Cidade de Origem"),
                ),
                (
                    "cidade_destino",
                    models.CharField(
                        max_length=100, verbose_name="Cidade(s) de Destino"
                    ),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Distância Percorrida (KM)",
                    ),
                ),
                (
                    "preco_combustivel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Preço Médio do Combustível (R$)",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor do Reembolso (R$)",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Objetivo"
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "PF"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.credor",
                        verbose_name="Beneficiário",
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reembolsos_combustivel",
                        to="verbas_indenizatorias.diaria",
                        verbose_name="Diária",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reembolsos_combustivel",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoReembolso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.tiposdedocumento",
                    ),
                ),
                (
                    "reembolso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.reembolsocombustivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento reembolso",
                "verbose_name_plural": "historical documento reembolsos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentoReembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=fluxo.models.caminho_documento,
                        validators=[fluxo.validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordem do arquivo"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fluxo.tiposdedocumento",
                    ),
                ),
                (
                    "reembolso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="verbas_indenizatorias.reembolsocombustivel",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalReembolsoCombustivel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_sequencial",
                    models.CharField(max_length=50, verbose_name="Número Sequencial"),
                ),
                ("data_saida", models.DateField(verbose_name="Data de Saída")),
                ("data_retorno", models.DateField(verbose_name="Data de Retorno")),
                (
                    "cidade_origem",
                    models.CharField(max_length=50, verbose_name="Cidade de Origem"),
                ),
                (
                    "cidade_destino",
                    models.CharField(
                        max_length=100, verbose_name="Cidade(s) de Destino"
                    ),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Distância Percorrida (KM)",
                    ),
                ),
                (
                    "preco_combustivel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Preço Médio do Combustível (R$)",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor do Reembolso (R$)",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Objetivo"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo": "PF"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.credor",
                        verbose_name="Beneficiário",
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.diaria",
                        verbose_name="Diária",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reembolso combustivel",
                "verbose_name_plural": "historical reembolso combustivels",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalJeton",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_sequencial",
                    models.CharField(max_length=50, verbose_name="Número Sequencial"),
                ),
                (
                    "reuniao",
                    models.CharField(
                        max_length=7, verbose_name="Reunião/Sessão de Referência"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo": "PF"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.credor",
                        verbose_name="Conselheiro(a)",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical jeton",
                "verbose_name_plural": "historical jetons",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDiaria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_solicitacao",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Concessão Inicial"),
                            ("PRORROGACAO", "Prorrogação"),
                            ("COMPLEMENTACAO", "Complementação"),
                        ],
                        default="INICIAL",
                        max_length=20,
                    ),
                ),
                ("data_saida", models.DateField(verbose_name="Data de Saída")),
                ("data_retorno", models.DateField(verbose_name="Data de Retorno")),
                (
                    "cidade_origem",
                    models.CharField(max_length=50, verbose_name="Cidade de Origem"),
                ),
                (
                    "cidade_destino",
                    models.CharField(
                        max_length=100, verbose_name="Cidade(s) de Destino"
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(max_length=200, verbose_name="Objetivo da Viagem"),
                ),
                (
                    "quantidade_diarias",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Quantidade de Diárias",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "autorizada",
                    models.BooleanField(default=False, verbose_name="Autorizada"),
                ),
                (
                    "numero_siscac",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="Nº SISCAC",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo": "PF"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.credor",
                        verbose_name="Beneficiário",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "proponente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proponente",
                    ),
                ),
                (
                    "meio_de_transporte",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.meiosdetransporte",
                        verbose_name="Meio de Transporte",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical diaria",
                "verbose_name_plural": "historical diarias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAuxilioRepresentacao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "numero_sequencial",
                    models.CharField(max_length=50, verbose_name="Número Sequencial"),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True,
                        help_text="Preencha se for representação em evento específico",
                        max_length=200,
                        null=True,
                        verbose_name="Evento/Motivo da Representação",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo": "PF"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="credores.credor",
                        verbose_name="Beneficiário",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fluxo.processo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.statuschoicesverbasindenizatorias",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical auxilio representacao",
                "verbose_name_plural": "historical auxilio representacaos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Tabela_Valores_Unitarios_Verbas_Indenizatorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cargo_funcao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="credores.cargosfuncoes",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="verbas_indenizatorias.tiposdeverbasindenizatorias",
                    ),
                ),
            ],
        ),
    ]
