# Generated by Django 6.0.3 on 2026-04-19 00:00

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verbas_indenizatorias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tiposdeverbasindenizatorias",
            options={
                "permissions": [
                    ("pode_visualizar_verbas", "Pode visualizar verbas indenizatórias"),
                    ("pode_gerenciar_jetons", "Pode gerenciar jetons"),
                    ("pode_agrupar_verbas", "Pode agrupar verbas indenizatórias"),
                    ("pode_gerenciar_processos_verbas", "Pode gerenciar processos de verbas"),
                    ("pode_gerenciar_auxilios", "Pode gerenciar auxílios"),
                    ("pode_gerenciar_reembolsos", "Pode gerenciar reembolsos"),
                    ("pode_autorizar_diarias", "Pode autorizar diárias"),
                    ("pode_importar_diarias", "Pode importar diárias"),
                    (
                        "pode_sincronizar_diarias_siscac",
                        "Pode sincronizar/importar diárias via SISCAC",
                    ),
                    ("pode_criar_diarias", "Pode criar diárias"),
                    ("pode_gerenciar_diarias", "Pode gerenciar diárias"),
                    (
                        "operar_prestacao_contas",
                        "Pode operar prestação de contas em nome de terceiros",
                    ),
                ]
            },
        ),
        migrations.AddField(
            model_name="diaria",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diarias_criadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiaria",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.CreateModel(
            name="ApostilaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_correcao", models.TextField(verbose_name="Texto da Apostila")),
                (
                    "campo_corrigido",
                    models.CharField(max_length=100, verbose_name="Campo Corrigido"),
                ),
                (
                    "valor_anterior",
                    models.TextField(blank=True, verbose_name="Valor Anterior"),
                ),
                ("valor_novo", models.TextField(blank=True, verbose_name="Valor Novo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "diaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apostilas",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=~models.Q(campo_corrigido__in=["valor_total", "quantidade_diarias"]),
                        name="apostila_nao_altera_valores_financeiros_chk",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="DevolucaoDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_devolvido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("data_devolucao", models.DateField()),
                ("motivo", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "diaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalApostilaDiaria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("texto_correcao", models.TextField(verbose_name="Texto da Apostila")),
                (
                    "campo_corrigido",
                    models.CharField(max_length=100, verbose_name="Campo Corrigido"),
                ),
                (
                    "valor_anterior",
                    models.TextField(blank=True, verbose_name="Valor Anterior"),
                ),
                ("valor_novo", models.TextField(blank=True, verbose_name="Valor Novo")),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical apostila diaria",
                "verbose_name_plural": "historical apostila diarias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDevolucaoDiaria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_devolvido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("data_devolucao", models.DateField()),
                ("motivo", models.TextField()),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical devolucao diaria",
                "verbose_name_plural": "historical devolucao diarias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
