# Generated by Django 6.0.3 on 2026-04-20 17:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbas_indenizatorias', '0002_alter_diaria_objetivo_alter_documentoauxilio_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContingenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('campo_corrigido', models.CharField(max_length=100, verbose_name='Campo Corrigido')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('valor_proposto', models.TextField(verbose_name='Valor Proposto')),
                ('status', models.CharField(choices=[('PENDENTE_SUPERVISOR', 'Pendente Supervisor'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE_SUPERVISOR', max_length=25)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Parecer')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contingência de Diária',
                'verbose_name_plural': 'Contingências de Diárias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContingenciaDiaria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('campo_corrigido', models.CharField(max_length=100, verbose_name='Campo Corrigido')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('valor_proposto', models.TextField(verbose_name='Valor Proposto')),
                ('status', models.CharField(choices=[('PENDENTE_SUPERVISOR', 'Pendente Supervisor'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE_SUPERVISOR', max_length=25)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Parecer')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Contingência de Diária',
                'verbose_name_plural': 'historical Contingências de Diárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='apostiladiaria',
            name='apostila_nao_altera_valores_financeiros_chk',
        ),
        migrations.AddField(
            model_name='contingenciadiaria',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contingencias_diaria_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contingenciadiaria',
            name='diaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contingencias', to='verbas_indenizatorias.diaria'),
        ),
        migrations.AddField(
            model_name='contingenciadiaria',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contingencias_diaria_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontingenciadiaria',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontingenciadiaria',
            name='diaria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verbas_indenizatorias.diaria'),
        ),
        migrations.AddField(
            model_name='historicalcontingenciadiaria',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontingenciadiaria',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='apostiladiaria',
            name='diaria',
        ),
        migrations.RemoveField(
            model_name='apostiladiaria',
            name='registrado_por',
        ),
        migrations.DeleteModel(
            name='HistoricalApostilaDiaria',
        ),
        migrations.DeleteModel(
            name='ApostilaDiaria',
        ),
    ]
