# Generated by Django 6.0.3 on 2026-04-19 00:00

import commons.shared.file_validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

from commons.shared.storage_utils import caminho_documento


class Migration(migrations.Migration):

    dependencies = [
        ("verbas_indenizatorias", "0002_diaria_criado_por_ledger_prestacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestacaoContasDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ABERTA", "Aberta"), ("ENCERRADA", "Encerrada")],
                        default="ABERTA",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("encerrado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "diaria",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestacao_contas",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "encerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestacoes_diaria_encerradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPrestacaoContasDiaria",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ABERTA", "Aberta"), ("ENCERRADA", "Encerrada")],
                        default="ABERTA",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("encerrado_em", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "diaria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.diaria",
                    ),
                ),
                (
                    "encerrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical prestacao contas diaria",
                "verbose_name_plural": "historical prestacao contas diarias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentoComprovacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=caminho_documento,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Ordem do arquivo",
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="verbas_indenizatorias.prestacaocontasdiaria",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalDocumentoComprovacao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.TextField(
                        max_length=100,
                        validators=[commons.shared.file_validators.validar_arquivo_seguro],
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Ordem do arquivo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verbas_indenizatorias.prestacaocontasdiaria",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pagamentos.tiposdedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento comprovacao",
                "verbose_name_plural": "historical documento comprovacaos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
