# Generated by Django 6.0.3 on 2026-05-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_credor_is_entidade_imune_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaturaMensal",
        ),
        migrations.DeleteModel(
            name="ContaFixa",
        ),
        migrations.DeleteModel(
            name="HistoricalFaturaMensal",
        ),
        migrations.DeleteModel(
            name="HistoricalContaFixa",
        ),
    ]
